# Product tagger with similarities

Because the expected proportion of products in our dataset is low and we need as much products as possible lets to try to come up with a way to select the subset of training set that would have a higher percentage of products. Also we would like for our model to have a good precision so it would be good to be tag many examples in the situations where this tagging is hard. First we create embeddings of our scrapped textual examples using OpenAI's ADA 002

In [8]:
import numpy as np
import pandas as pd
import openai
import math
from config_book import furniture_list

In [9]:
openai.api_key = '###########'
EMBEDDING_MODEL = "text-embedding-ada-002"

In [10]:
def get_embedding(text: str, model: str = EMBEDDING_MODEL) -> List[float]:
    """
    Gets the embedding vector for a given text using the specified model.

    Args:
        text (str): The text to get the embedding for.
        model (str, optional): The model name for embedding. Default is "text-embedding-ada-002".

    Returns:
        List[float]: The embedding vector.

    """
    return openai.Embedding.create(input=[text], model=model)['data'][0]['embedding']

Since this needed to be done in step by step fashion we did this using the ada_embedder.py (src.label.ada_embedder) and now we just load the embeddings

In [11]:
df = pd.read_pickle('../data/ada_embeddings.pkl')

In [12]:
df.head()

                clean                                      ada_embedding
0     3 Drawer Chests  [-0.009600184857845306, 0.001654650317505002, ...
1  Eau Rouge Armchair  [-0.008347862400114536, -0.009867465123534203,...
2  Entryway & Mudroom  [0.010682865977287292, 0.008147293701767921, -...
3      Kenneth Nilson  [-0.012051408179104328, -0.019119305536150932,...
4              Dania   [-0.009124724194407463, 0.003880592528730631, ...

The idea is as follows. Lets get 50 most standard names of furniture and embed them as well (this imported at the first cell of this notebook). Now let's calculate similarities between our examples and all of this 50 vectors. We will also make an average vector out of our standard 50 furniture vectors and calculate similarities between our examples and this vector. So the idea is that vectors which are likely to be furniture product names need to have at least some level of similarity with this average vector (think of this vector as a vector that represents general notion of furniture). But on the other side we don't want that our examples be to close to the any of 50 standard furniture names because this would lead to the picking too much of the general furniture names and not particular products (for example having just 'wooden chairs' would be too close to 'chairs' which is probably scraped from some drop down menu on web page where you can select types of furniture. On the other hand Veridon Garden Chair would not be too close to chairs but on the other side similar enough to average furniture vector to be selected). So in the nest couple of cells we will calculate these similarities and then try to find the best thresholds

Let's try both euclidean and cosine similarity

In [13]:
def euclidean_similarity(df, embeddings_column, desired_vector):
    df_copy = df.copy()
    # Convert the embeddings column to a NumPy array
    embeddings_array = np.array(df_copy[embeddings_column].tolist())
    desired_vector_array = np.array(desired_vector)

    # Calculate the Euclidean distances
    distances = np.linalg.norm(embeddings_array - desired_vector_array, axis=1)

    # Calculate the similarities as the inverse of distances
    similarities = 1 / (1 + distances)

    # Add the similarities as a new column in the DataFrame
    df_copy['similarity'] = similarities

    return df_copy.similarity

In [14]:
def cosine_similarity(df, embeddings_column, desired_vector):
    df_copy = df.copy()
    # Convert the embeddings column to a NumPy array
    embeddings_array = np.array(df_copy[embeddings_column].tolist())
    desired_vector_array = np.array(desired_vector)

    # Calculate the cosine similarities
    similarities = np.dot(embeddings_array, desired_vector_array)

    # Add the similarities as a new column in the DataFrame
    df_copy['similarity'] = similarities

    return df_copy.similarity

In [ ]:
for furniture in furniture_list:
    emb = get_embedding(furniture, model=EMBEDDING_MODEL)
    df_emb[f'{furniture}_euc'] = euclidean_similarity(df_emb, 'ada_embedding', emb)
    df_emb[f'{furniture}_cos'] = cosine_similarity(df_emb, 'ada_embedding', emb)

df_emb.to_pickle('../data/similarities.pkl')

In [15]:
df = pd.read_pickle('../data/similarities.pkl')

In [16]:
df.head()

,clean,ada_embedding,Desk_euc,Desk_cos,Chair_euc,Chair_cos,Table_euc,Table_cos,Sofa_euc,Sofa_cos,...,Display cabinet_euc,Display cabinet_cos,Sideboard_euc,Sideboard_cos,Lounge chair_euc,Lounge chair_cos,Buffet_euc,Buffet_cos,Credenza desk_euc,Credenza desk_cos
0,3 Drawer Chests,"[-0.009600184857845306, 0.001654650317505002, ...",0.627515,0.823828,0.612736,0.800272,0.607625,0.791502,0.618653,0.810017,...,0.656127,0.862662,0.610107,0.795804,0.609207,0.794252,0.602361,0.782111,0.655236,0.861573
1,Eau Rouge Armchair,"[-0.008347862400114536, -0.009867465123534203,...",0.617648,0.808391,0.637967,0.838984,0.600940,0.779512,0.635550,0.835583,...,0.612893,0.800537,0.590949,0.760434,0.667201,0.875599,0.602947,0.783176,0.622063,0.815439
2,Entryway & Mudroom,"[0.010682865977287292, 0.008147293701767921, -...",0.620073,0.812291,0.611084,0.797475,0.608514,0.793052,0.618333,0.809500,...,0.624907,0.819856,0.611130,0.797552,0.618773,0.810209,0.598747,0.775446,0.632679,0.831463
3,Kenneth Nilson,"[-0.012051408179104328, -0.019119305536150932,...",0.595738,0.769757,0.603267,0.783754,0.590150,0.758846,0.585474,0.749356,...,0.587580,0.753671,0.583402,0.745043,0.592697,0.763876,0.592647,0.763778,0.587657,0.753828
4,Dania,"[-0.009124724194407463, 0.003880592528730631, ...",0.600226,0.778196,0.600979,0.779584,0.589548,0.757642,0.604173,0.785385,...,0.589272,0.757089,0.576662,0.730534,0.597896,0.773850,0.592508,0.763506,0.595460,0.769225

Lets create average vector for furniture type

In [17]:
sum_vec = []
for furniture in furniture_list:
    sum_vec.append(get_embedding(furniture, model='text-embedding-ada-002'))
    avg_vec = np.average(np.array(sum_vec), axis=0)

Lets add similarities with average vector

In [18]:
df['avg_euc'] = euclidean_similarity(df, 'ada_embedding', avg_vec)

/var/folders/yw/f9bv06657hd27p6dc_53ct000000gn/T/ipykernel_97092/3954473577.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['avg_euc'] = euclidean_similarity(df, 'ada_embedding', avg_vec)

In [19]:
df['avg_cos'] = cosine_similarity(df, 'ada_embedding', avg_vec)

/var/folders/yw/f9bv06657hd27p6dc_53ct000000gn/T/ipykernel_97092/789758034.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['avg_cos'] = cosine_similarity(df, 'ada_embedding', avg_vec)

In [20]:
df.describe()

,Desk_euc,Desk_cos,Chair_euc,Chair_cos,Table_euc,Table_cos,Sofa_euc,Sofa_cos,Bookshelf_euc,Bookshelf_cos,...,Sideboard_euc,Sideboard_cos,Lounge chair_euc,Lounge chair_cos,Buffet_euc,Buffet_cos,Credenza desk_euc,Credenza desk_cos,avg_euc,avg_cos
count,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,...,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000,78664.000000
mean,0.603798,0.783331,0.605318,0.786083,0.598876,0.774464,0.606619,0.787517,0.604444,0.784511,...,0.588475,0.754176,0.605814,0.785734,0.594730,0.766839,0.605154,0.784767,0.651793,0.777824
std,0.014437,0.026211,0.014400,0.025627,0.013421,0.024888,0.018779,0.031858,0.014386,0.025953,...,0.013369,0.026601,0.020341,0.033872,0.011810,0.022969,0.019111,0.033460,0.019143,0.024773
min,0.408508,-0.048254,0.409374,-0.040766,0.408917,-0.044713,0.409201,-0.042256,0.410290,-0.032914,...,0.410061,-0.034871,0.408376,-0.049398,0.409354,-0.040941,0.410908,-0.027657,0.418983,-0.039275
25%,0.593955,0.766326,0.595924,0.770113,0.590501,0.759545,0.593885,0.766190,0.594661,0.767690,...,0.579762,0.737299,0.592569,0.763626,0.587740,0.753997,0.591224,0.760979,0.638229,0.761584
50%,0.601411,0.780377,0.603068,0.783394,0.597036,0.772228,0.603173,0.783584,0.603228,0.783684,...,0.586992,0.752472,0.601580,0.780686,0.593819,0.766062,0.600408,0.778533,0.648274,0.775051
75%,0.612353,0.799627,0.612300,0.799537,0.604426,0.785840,0.616066,0.805810,0.612859,0.800480,...,0.595862,0.769994,0.614275,0.802848,0.600768,0.779196,0.617314,0.807849,0.663601,0.793746
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.998372,0.999999,...,1.000000,1.000000,0.998618,0.999999,1.000000,1.000000,0.800319,0.968874,0.768145,0.876682

We will take cosine distance first because of we have a larger variation with this metric.

In [21]:
# Cosine columns without average vector

cos_col = [col for col in df.columns if (col.endswith('cos') and not col.startswith('avg_'))]

Since we have a lot of examples un order to get the best thresholds quick we will take a reasonably sized random sample with concrete threshold levels of similarities. The size is governed by the condition that we can use normal distribution approximation and that confidence intervals are reasonably narrow.

In [22]:
# This function returns a sample satisfying the given thresholds

def similarity_sampler(df, text_columnn, upper, lower, sample_size):
    condition1 = (df[cos_col] < upper).all(axis=1)
    condition2 = df['avg_cos'] > lower
    result = condition1 & condition2
    out = df[result][text_columnn]
    print(f'Number of tokens satisfying the condition is {out.size} \n')
    return out.sample(sample_size, random_state=2023)

In [23]:
# This function helps us annotate products and informs us in the end about the percentage of positive samples,
# validity of normal distribution approximation, and width of confidence interval 

def tag_estimator(data):
    num_samples = data.size
    print(f'Data size is {num_samples} \n')
    pos_proportion = 0
    for example in data:
        try:
            annotation = input(f'Is "{example}" a product? (1 - yes, 0 - no)')
            annotation = int(annotation)
            assert annotation == 0 or annotation == 1
            pos_proportion = pos_proportion + annotation/num_samples
        except (AssertionError, ValueError) as e:
            num_samples = num_samples - 1
            print("Input only zeros and ones")
            continue
    if (num_samples*pos_proportion <= 5) or (num_samples*(1-pos_proportion) <= 5):
        print('Normal distribution approximation not valid')
        return
    # 95% confidence
    sam_var = 1.96 * math.sqrt((pos_proportion * (1-pos_proportion))/num_samples)
    print(f'Percentage of positive examples is {pos_proportion*100}% +/- {sam_var*100}% with 95% confidence')

Lets try 0.9, 0.8 and sample size of 100

In [18]:
data = similarity_sampler(df, 'clean', 0.9, 0.8, 100)
tag_estimator(data)

Data size is 100

Is "Teak framed dining chair with woven PE seat " a product? (1 - yes, 0 - no)0
Is "Rattan 2 5 seater lounge with upholstered seat and " a product? (1 - yes, 0 - no)0
Is "Bedroom Furniture" a product? (1 - yes, 0 - no)0
Is "Includes 4 Spacious Drawers" a product? (1 - yes, 0 - no)0
Is "Headboard Grand - Bellus Furniture" a product? (1 - yes, 0 - no)1
Is "Whitewood Desk Apato Melbourne Japanese Furniture Richmond 3121" a product? (1 - yes, 0 - no)1
Is "DINING ROOMS" a product? (1 - yes, 0 - no)0
Is "Dimensions 95 25 W x 16 5 D x 14 H" a product? (1 - yes, 0 - no)0
Is "Small 2 Door 1 Drawer Sideboard" a product? (1 - yes, 0 - no)0
Is "Velvet Cushion Brown " a product? (1 - yes, 0 - no)0
Is "Mid Century Dressers & Chest of Drawers" a product? (1 - yes, 0 - no)0
Is "Essence Sideboard" a product? (1 - yes, 0 - no)0
Is "Reclaimed Bar Furniture" a product? (1 - yes, 0 - no)0
Is "Cybil armchair" a product? (1 - yes, 0 - no)1
Is "Fleur dining chair - white" a product? (1 - yes, 0 - no)0
Is "Alamakee Kitchen Bench" a product? (1 - yes, 0 - no)1
Is "5 Pc - Dresser Mirror Panel Headboard 2 Nightstands" a product? (1 - yes, 0 - no)0
Is "Sorensen teak bench" a product? (1 - yes, 0 - no)1
Is "Avery Armchair" a product? (1 - yes, 0 - no)1
Is "New Launch Sofas" a product? (1 - yes, 0 - no)0
Is "Wine & Spirit Cabinets" a product? (1 - yes, 0 - no)0
Is "Jorca Highback Office Chair" a product? (1 - yes, 0 - no)1
Is "Rohes Bench in cognac leatherette" a product? (1 - yes, 0 - no)1
Is "LeMon Oak 2 Drawer Bedisde Cabinet George Street Furnishers" a product? (1 - yes, 0 - no)1
Is "Click Dining Chair with Armrests" a product? (1 - yes, 0 - no)1
Is " Description" a product? (1 - yes, 0 - no)0
Is "Rugs " a product? (1 - yes, 0 - no)0
Is "Bennington Swivel Bar Chair" a product? (1 - yes, 0 - no)1
Is "6 Drawer 1 Door" a product? (1 - yes, 0 - no)0
Is "Lewis Adjustable Stool" a product? (1 - yes, 0 - no)1
Is "Headboard has storage inside" a product? (1 - yes, 0 - no)0
Is "3 Pc Bedroom Set" a product? (1 - yes, 0 - no)0
Is "Delta Rattan Dining Chair" a product? (1 - yes, 0 - no)1
Is "Three drawers with undermount soft-close drawer guides " a product? (1 - yes, 0 - no)0
Is "Velvet beds" a product? (1 - yes, 0 - no)0
Is "Occasional and Accent Tables" a product? (1 - yes, 0 - no)0
Is "Cherry finish" a product? (1 - yes, 0 - no)0
Is "Artiss 4 Chest of Drawers Tallboy Dre " a product? (1 - yes, 0 - no)1
Is "Teak Sideboards" a product? (1 - yes, 0 - no)0
Is "Nexa Nesting Side Table" a product? (1 - yes, 0 - no)1
Is "A conversational chair is the perfect place to park after a long day " a product? (1 - yes, 0 - no)0
Is "Soma Height Adjustable Large Lift Desk" a product? (1 - yes, 0 - no)1
Is "Sofa Set in Walnut" a product? (1 - yes, 0 - no)0
Is "Arden Grace On Wheels Modern Coffee Table " a product? (1 - yes, 0 - no)1
Is "Lark dining table 94 " a product? (1 - yes, 0 - no)1
Is "Skrivbord" a product? (1 - yes, 0 - no)0
Is "Procyon Garden Pallet Corner Sofa Brown Impregnated Pinewood" a product? (1 - yes, 0 - no)1
Is "2 Pc Chairs" a product? (1 - yes, 0 - no)0
Is "Gretchen Chair" a product? (1 - yes, 0 - no)1
Is "Mirror for Dresser W42 x D1 x H40 " a product? (1 - yes, 0 - no)0
Is "St Mark s High Bent Feather Chair" a product? (1 - yes, 0 - no)1
Is "Austell Farmhouse Chair" a product? (1 - yes, 0 - no)1
Is "Chandeliers" a product? (1 - yes, 0 - no)0
Is "Noir Havana Sideboard" a product? (1 - yes, 0 - no)1
Is "Kitchen Mats" a product? (1 - yes, 0 - no)0
Is "Lounge & Cafe" a product? (1 - yes, 0 - no)0
Is "Cutlery" a product? (1 - yes, 0 - no)0
Is "Yorkshire TV Console" a product? (1 - yes, 0 - no)1
Is "Eetkamerstoelen" a product? (1 - yes, 0 - no)0
Is "Scandinavian Chest of Drawers" a product? (1 - yes, 0 - no)0
Is "Badalona I Beige Love Seat" a product? (1 - yes, 0 - no)1
Is "My Console" a product? (1 - yes, 0 - no)0
Is "Plinths" a product? (1 - yes, 0 - no)0
Is "Swanson office chair" a product? (1 - yes, 0 - no)1
Is "Monaco end table" a product? (1 - yes, 0 - no)1
Is "Feast Banquet Table - Round" a product? (1 - yes, 0 - no)1
Is "Ash Loveseat" a product? (1 - yes, 0 - no)1
Is "Bed Frames" a product? (1 - yes, 0 - no)0
Is "Solid timber dining chair with your choice of " a product? (1 - yes, 0 - no)0
Is "Drummond Mirrored Dresser" a product? (1 - yes, 0 - no)1
Is "In Stock Living Room" a product? (1 - yes, 0 - no)0
Is "Flat Pack Bedroom Furniture" a product? (1 - yes, 0 - no)0
Is "All Teakco Furniture" a product? (1 - yes, 0 - no)0
Is "Armelle TV Media Console" a product? (1 - yes, 0 - no)1
Is " Carved Chair " a product? (1 - yes, 0 - no)0
Is "Ecs Breakfront Bookcase" a product? (1 - yes, 0 - no)1
Is "Bedspreads" a product? (1 - yes, 0 - no)0
Is "Slim Extendable" a product? (1 - yes, 0 - no)0
Is "Rattan Bedroom Furniture" a product? (1 - yes, 0 - no)0
Is "Arden Grace Antique Style 4 Drawer Mango Wood Coffee Table" a product? (1 - yes, 0 - no)1
Is "Fuentes dining table 86 " a product? (1 - yes, 0 - no)1
Is "Sidra Outdoor Bar Stool" a product? (1 - yes, 0 - no)1
Is "Step top with shaped block feet" a product? (1 - yes, 0 - no)0
Is "FDB Moebler" a product? (1 - yes, 0 - no)0
Is "Finn All Wood Armchair" a product? (1 - yes, 0 - no)1
Is "Delca ottoman beanbag" a product? (1 - yes, 0 - no)1
Is "Column Floor" a product? (1 - yes, 0 - no)0
Is "Kids Beds" a product? (1 - yes, 0 - no)0
Is "Bertoia stool" a product? (1 - yes, 0 - no)1
Is "Large timber table with chucky 120mm box leg " a product? (1 - yes, 0 - no)0
Is "Taunton Dining Chair" a product? (1 - yes, 0 - no)1
Is "Rexton 1-Seater Sofa" a product? (1 - yes, 0 - no)1
Is "Bastingage Gray Loveseat" a product? (1 - yes, 0 - no)1
Is "Desk Tidy A" a product? (1 - yes, 0 - no)0
Is "Industrial Dining Furniture" a product? (1 - yes, 0 - no)0
Is "Carmel Coffee Table" a product? (1 - yes, 0 - no)1
Is "Tivat 2 floor lamp" a product? (1 - yes, 0 - no)1
Is "Designer Office Table - 4" a product? (1 - yes, 0 - no)1
Is "Ennis Upholstered Arm Chair" a product? (1 - yes, 0 - no)1
Is "Barkerville 2-Drawer Corner TV Cabinet" a product? (1 - yes, 0 - no)1
Percentage of positive examples is 46.00000000000002% +/- 9.768589662791657% with 95% confidence

Now we go lower to 0.85 and 0.75

In [19]:
data = similarity_sampler(df, 'clean', 0.85, 0.75, 100)
tag_estimator(data)

Data size is 100

Is "91cm" a product? (1 - yes, 0 - no)0
Is "662896040241" a product? (1 - yes, 0 - no)0
Is "Pocket springs HR Foam 35 kg" a product? (1 - yes, 0 - no)0
Is " Sales " a product? (1 - yes, 0 - no)0
Is "Cymax" a product? (1 - yes, 0 - no)0
Is "Jul 18 2019" a product? (1 - yes, 0 - no)0
Is "French Polynesia" a product? (1 - yes, 0 - no)0
Is "info tove-kindt-larsen 1" a product? (1 - yes, 0 - no)
Input only zeros and ones
Is "Pebble wall ceilling" a product? (1 - yes, 0 - no)0
Is "1 969 00" a product? (1 - yes, 0 - no)0
Is "$2 600 00" a product? (1 - yes, 0 - no)0
Is "White - $640 00 AUD" a product? (1 - yes, 0 - no)0
Is "Belle Champagne Silver Finish" a product? (1 - yes, 0 - no)0
Is "Landscape Votive Sage Amber" a product? (1 - yes, 0 - no)1
Is "TAPER CANDLES" a product? (1 - yes, 0 - no)0
Is "Unique foot glides" a product? (1 - yes, 0 - no)0
Is "CHAIRS Chairs Contracts forms Forms Nissin Mokkou Seating" a product? (1 - yes, 0 - no)0
Is "00656237701007" a product? (1 - yes, 0 - no)0
Is "Grey Boucle Fabric Bench PEYTON 117Grey Meridian Modern Contemporary" a product? (1 - yes, 0 - no)1
Is "Christmas Island " a product? (1 - yes, 0 - no)0
Is "Showroom" a product? (1 - yes, 0 - no)0
Is "From $423" a product? (1 - yes, 0 - no)0
Is "10 L x 6 W" a product? (1 - yes, 0 - no)0
Is "46524" a product? (1 - yes, 0 - no)0
Is "Welcome to the Innerspace Design & Art Prize 2022 " a product? (1 - yes, 0 - no)0
Is "Modern Faucets " a product? (1 - yes, 0 - no)0
Is "The item was splendid The packaging was exceptionally nice " a product? (1 - yes, 0 - no)0
Is "Ms Nedra Treutel MD" a product? (1 - yes, 0 - no)0
Is "Usefull Links" a product? (1 - yes, 0 - no)0
Is "Bay Brown" a product? (1 - yes, 0 - no)0
Is "Base material Steel" a product? (1 - yes, 0 - no)0
Is "Canvases - FADS" a product? (1 - yes, 0 - no)0
Is "Save $7 35" a product? (1 - yes, 0 - no)0
Is "$1 799 00" a product? (1 - yes, 0 - no)0
Is "Portmagee Glider" a product? (1 - yes, 0 - no)0
Is "Color Finish " a product? (1 - yes, 0 - no)0
Is "Tahoe Media Stand" a product? (1 - yes, 0 - no)1
Is "Europa Pendant" a product? (1 - yes, 0 - no)1
Is "Armelle Living Room Set" a product? (1 - yes, 0 - no)1
Is "The item was superb The packaging was remarkably effective " a product? (1 - yes, 0 - no)0
Is "Light Brown Cristal Panel Bedroom Set 3 PCS" a product? (1 - yes, 0 - no)0
Is "2070" a product? (1 - yes, 0 - no)0
Is "4 213 44" a product? (1 - yes, 0 - no)0
Is "Remarkably superior quality The packaging was ever so neat " a product? (1 - yes, 0 - no)0
Is "Superior Craftsmanship" a product? (1 - yes, 0 - no)0
Is "From $8277" a product? (1 - yes, 0 - no)0
Is "Alize Reinger" a product? (1 - yes, 0 - no)0
Is "From $3760" a product? (1 - yes, 0 - no)0
Is "Abbie VerticalWall Bed Murphy Bed 20 DEEP" a product? (1 - yes, 0 - no)1
Is " PENS " a product? (1 - yes, 0 - no)0
Is "Kathryne Cassin" a product? (1 - yes, 0 - no)0
Is "sales modshop1 com" a product? (1 - yes, 0 - no)0
Is "Currency" a product? (1 - yes, 0 - no)0
Is "H5 4 x " a product? (1 - yes, 0 - no)0
Is "ETHNICRAFT" a product? (1 - yes, 0 - no)0
Is "Queen Bed 68 x 96 x 72 H" a product? (1 - yes, 0 - no)0
Is "Recently viewed" a product? (1 - yes, 0 - no)0
Is "BUDAPEST" a product? (1 - yes, 0 - no)0
Is "Choose Colour Cushion" a product? (1 - yes, 0 - no)0
Is "View all" a product? (1 - yes, 0 - no)0
Is "Laundry Box Collection" a product? (1 - yes, 0 - no)0
Is "$ 813 00" a product? (1 - yes, 0 - no)0
Is "Sunbrella Dupione Sand Outdoor Curtain with Grommets" a product? (1 - yes, 0 - no)1
Is "$3 398 00" a product? (1 - yes, 0 - no)0
Is "5 176 00" a product? (1 - yes, 0 - no)0
Is "Stylos" a product? (1 - yes, 0 - no)0
Is "From $614" a product? (1 - yes, 0 - no)0
Is "$2 310 00" a product? (1 - yes, 0 - no)0
Is "Blog" a product? (1 - yes, 0 - no)0
Is "2 085 00" a product? (1 - yes, 0 - no)0
Is "Stainless Steel Accents & Legs" a product? (1 - yes, 0 - no)0
Is "Fazeek" a product? (1 - yes, 0 - no)0
Is "Reflections" a product? (1 - yes, 0 - no)0
Is "Make an enquiry" a product? (1 - yes, 0 - no)0
Is "Madden" a product? (1 - yes, 0 - no)0
Is "Messina Sectional" a product? (1 - yes, 0 - no)0
Is "Trading Hours " a product? (1 - yes, 0 - no)0
Is "Customer Favourites" a product? (1 - yes, 0 - no)0
Is "waste paper baskets" a product? (1 - yes, 0 - no)0
Is "5 164 60" a product? (1 - yes, 0 - no)0
Is "193 99" a product? (1 - yes, 0 - no)0
Is "SORENSEN TEAK BENCH PACKAGE 100CM 120CM 150CM" a product? (1 - yes, 0 - no)0
Is " Highly breathable" a product? (1 - yes, 0 - no)0
Is "From $1503" a product? (1 - yes, 0 - no)0
Is "Outdoor Furniture Accessories by Countryside Amish Furniture" a product? (1 - yes, 0 - no)0
Is "9897" a product? (1 - yes, 0 - no)0
Is "Silky Loop Rug - 6 x 9 " a product? (1 - yes, 0 - no)0
Is "224 99" a product? (1 - yes, 0 - no)0
Is "W 725" a product? (1 - yes, 0 - no)0
Is " 3 0 kg" a product? (1 - yes, 0 - no)0
Is "Contact Our Team" a product? (1 - yes, 0 - no)0
Is "Price Match Guarantee" a product? (1 - yes, 0 - no)0
Is "Add 5 Year Warranty $405 42 " a product? (1 - yes, 0 - no)0
Is "Mar 11 2020" a product? (1 - yes, 0 - no)0
Is "Leather - Brompton Brown - $6 360 00 USD" a product? (1 - yes, 0 - no)0
Is "Naima collection By Acme" a product? (1 - yes, 0 - no)0
Is "Cateye console" a product? (1 - yes, 0 - no)1
Is "Akova wall light" a product? (1 - yes, 0 - no)1
Is "Window Pane Grey Black B " a product? (1 - yes, 0 - no)1
Is "FINISHES & FABRICS" a product? (1 - yes, 0 - no)0
Percentage of positive examples is 10.1010101010101% +/- 5.936060010453508% with 95% confidence

Let's refine with 0.87 and 0.8

In [20]:
data = similarity_sampler(df, 'clean', 0.87, 0.8, 100)
tag_estimator(data)

Data size is 100

Is "Antique Small Oval Footstool" a product? (1 - yes, 0 - no)1
Is "Nest of Tables" a product? (1 - yes, 0 - no)0
Is "Tegmen Modern White Bed Frame " a product? (1 - yes, 0 - no)1
Is "Brinkley Double Chest Armoire" a product? (1 - yes, 0 - no)1
Is "8770 Accent Table" a product? (1 - yes, 0 - no)1
Is "Aiden 3-Seater Sofa" a product? (1 - yes, 0 - no)1
Is "Mirrored front and end panels " a product? (1 - yes, 0 - no)0
Is "Tray " a product? (1 - yes, 0 - no)0
Is "Arch console" a product? (1 - yes, 0 - no)1
Is "Wall Clock" a product? (1 - yes, 0 - no)0
Is "Jenny Crossback Armchair Antique Oak" a product? (1 - yes, 0 - no)1
Is "Apex Study Table - W1800" a product? (1 - yes, 0 - no)1
Is "Bertoia Molded Shell Side Chair - Stacking" a product? (1 - yes, 0 - no)1
Is "Vegas small extendable table" a product? (1 - yes, 0 - no)1
Is "Linear Steel Bench" a product? (1 - yes, 0 - no)0
Is "Rockville Office Set" a product? (1 - yes, 0 - no)1
Is "Main menu" a product? (1 - yes, 0 - no)0
Is "Your home office The living room A studio bedroom " a product? (1 - yes, 0 - no)0
Is "Upholstered with quality faux linen fabric" a product? (1 - yes, 0 - no)0
Is "Modrest Dustin Collection" a product? (1 - yes, 0 - no)0
Is "Wickham Wingback Chair Blue Stripe " a product? (1 - yes, 0 - no)1
Is "Medium Back Chair - Brownie" a product? (1 - yes, 0 - no)1
Is "Kids Bedroom" a product? (1 - yes, 0 - no)0
Is "Ercol Windsor IR TV Cabinet" a product? (1 - yes, 0 - no)1
Is "2 Pc Power Reclining Sofa Loveseat" a product? (1 - yes, 0 - no)0
Is " LELE Counter Chair" a product? (1 - yes, 0 - no)1
Is "Collaborative Furniture - 9" a product? (1 - yes, 0 - no)0
Is "Dave Sofa" a product? (1 - yes, 0 - no)1
Is "This stand is " a product? (1 - yes, 0 - no)0
Is "Contemporary Sofa - 19" a product? (1 - yes, 0 - no)1
Is "Chair collection from Cintique- Dillamore s Furnishers" a product? (1 - yes, 0 - no)0
Is "Decoration " a product? (1 - yes, 0 - no)0
Is "Bedspreads" a product? (1 - yes, 0 - no)0
Is "Adona Adonica Fusion Bedside Table w Drawer in Plywood" a product? (1 - yes, 0 - no)1
Is "Mudroom & Entryway Furniture" a product? (1 - yes, 0 - no)0
Is "Solid Wood Hope Chests & Storage Seats" a product? (1 - yes, 0 - no)0
Is "Chill Sectional" a product? (1 - yes, 0 - no)0
Is "Nest Small Sectional Sofa" a product? (1 - yes, 0 - no)1
Is "Etienne Mirrored Console Table 2-Drawer Modern Parisian" a product? (1 - yes, 0 - no)1
Is "Bodine Bergere Chair Linen " a product? (1 - yes, 0 - no)1
Is "Velvet single bed" a product? (1 - yes, 0 - no)0
Is "Bedsides" a product? (1 - yes, 0 - no)0
Is "Product" a product? (1 - yes, 0 - no)0
Is "Flatpack AffordableBedside" a product? (1 - yes, 0 - no)0
Is "Small and practical " a product? (1 - yes, 0 - no)0
Is "Cart" a product? (1 - yes, 0 - no)0
Is "Paon Outdoor Dining Chair" a product? (1 - yes, 0 - no)1
Is "Rustic Live Edge Living Room Tables & Stands" a product? (1 - yes, 0 - no)0
Is "Sergei Table Light" a product? (1 - yes, 0 - no)1
Is "Bench Cushions" a product? (1 - yes, 0 - no)0
Is "Federico Mustard Velvet Armchair" a product? (1 - yes, 0 - no)1
Is "Share" a product? (1 - yes, 0 - no)0
Is "DESK CHAIRS" a product? (1 - yes, 0 - no)0
Is "Bergen Nest of Tables" a product? (1 - yes, 0 - no)1
Is "Patio Bar Furniture" a product? (1 - yes, 0 - no)0
Is "Wizard Single High Sleeper Bed Workstation White" a product? (1 - yes, 0 - no)1
Is "Huntington Butterfly Leaf Table" a product? (1 - yes, 0 - no)1
Is "Mood Footstool" a product? (1 - yes, 0 - no)1
Is "Criss Cross Back Carver Dining Chair" a product? (1 - yes, 0 - no)1
Is "Wall art " a product? (1 - yes, 0 - no)0
Is "Angel Single Bed with Underbed Drawer " a product? (1 - yes, 0 - no)1
Is "2 Pc Left Arm Facing Corner Chair" a product? (1 - yes, 0 - no)0
Is "Upholstered beds" a product? (1 - yes, 0 - no)0
Is "Cleavon Chocolate Espresso Ottoman" a product? (1 - yes, 0 - no)1
Is "Brinkley Bedroom Chest" a product? (1 - yes, 0 - no)1
Is "Biddeford Bow Back Chair" a product? (1 - yes, 0 - no)1
Is "Chelsea White Gloss & Truffle Oak Dressing Table" a product? (1 - yes, 0 - no)1
Is "Elize 2 Door Cabinet Sideboard Champagne Detailing" a product? (1 - yes, 0 - no)1
Is "Coronado Corner TV Stand" a product? (1 - yes, 0 - no)1
Is "Lawrence Peabody Chairs Sofa s Selig collection Nemchoff collection" a product? (1 - yes, 0 - no)1
Is "Traditional Bedroom Set" a product? (1 - yes, 0 - no)0
Is "2 Pc - Reclining Sofa Loveseat" a product? (1 - yes, 0 - no)0
Is "Outlet" a product? (1 - yes, 0 - no)0
Is "Curved Bench tm " a product? (1 - yes, 0 - no)0
Is "Timber cube stool with fixed upholstered seat pad " a product? (1 - yes, 0 - no)0
Is "Drawers 6" a product? (1 - yes, 0 - no)0
Is "Bedheads" a product? (1 - yes, 0 - no)0
Is "Menu " a product? (1 - yes, 0 - no)0
Is "Novena Furniture" a product? (1 - yes, 0 - no)0
Is "The shop specializes in quality furniture at unbeatable prices " a product? (1 - yes, 0 - no)0
Is "Adirondack Chairs Combo" a product? (1 - yes, 0 - no)1
Is "4 Pc - Dresser Mirror Chest Panel Headboard" a product? (1 - yes, 0 - no)0
Is "Theater Seating " a product? (1 - yes, 0 - no)1
Is "Cushion & Cushion Covers" a product? (1 - yes, 0 - no)0
Is "Table W1100 x D180 x H680mm " a product? (1 - yes, 0 - no)0
Is "Vogue Cocktail Pastel Pink Armchair" a product? (1 - yes, 0 - no)1
Is "Removable laminated marble top" a product? (1 - yes, 0 - no)0
Is "Manda Dining Chair" a product? (1 - yes, 0 - no)1
Is "Sandra dining chair grey fabric" a product? (1 - yes, 0 - no)1
Is "Toolbox" a product? (1 - yes, 0 - no)0
Is "Skovby Portable Bar" a product? (1 - yes, 0 - no)1
Is "8 x 11 6 " a product? (1 - yes, 0 - no)0
Is "Drawer Dimensions" a product? (1 - yes, 0 - no)0
Is "Wall Decor" a product? (1 - yes, 0 - no)0
Is "Siesta 302 Classic Chair" a product? (1 - yes, 0 - no)1
Is "Button Tufted Headboard " a product? (1 - yes, 0 - no)0
Is "Finn Metal Wood Armchair" a product? (1 - yes, 0 - no)1
Is "Anona Corner Hutch" a product? (1 - yes, 0 - no)1
Is "STELLA - Aluminum chair" a product? (1 - yes, 0 - no)1
Is "Baby Change Tables" a product? (1 - yes, 0 - no)0
Percentage of positive examples is 47.00000000000003% +/- 9.78234409535874% with 95% confidence

In the end 0.87 and 0.8 seem to be good enough

In [23]:
data = similarity_sampler(df, 'clean', 0.87, 0.8, 100)

Number of tokens satisfying the condition is 6024

Now that we have a set with high proportion of products lets tag 1000 examples

In [1]:
def product_tagger(df, text_columnn, upper, lower):
    df_copy = df.copy()
    condition1 = (df_copy[cos_col] < upper).all(axis=1)
    condition2 = df_copy['avg_cos'] > lower
    result = condition1 & condition2
    df_copy = df_copy[result]
    print(f'Number of tokens satisfying the condition is {df_copy.shape[0]} \n')
    num_samples = df_copy.size
    i = 0
    for ind, example in df[result][text_columnn].items():
        try:
            annotation = input(f'Is "{example}" a product? (1 - yes, 0 - no)')
            annotation = int(annotation)
            assert annotation == 0 or annotation == 1
            df_copy.at[ind, 'tag'] = annotation
        except (AssertionError, ValueError) as e:
            num_samples = num_samples - 1
            print("Input only zeros and ones")
            continue
        i = i + 1
        if i%100 == 0:
            save = input(f'You have {i} examples. Do you want to save (y/n)?')
            if save == 'y':
                df_copy.to_csv(f'labeled_set_{100*lower}_{100*upper}.csv')
    print(df_copy)

Unfortenately I have accidentaly deleted the results of tagging but those can be seen in the <b> similarities.pdf </b> in this same folder. This is just for these 1000 examples the rest are here

In [2]:
product_tagger(df, 'clean', 0.87, 0.8)

NameError: name 'df' is not defined

Now lets add some data that has high similarity with standard furniture names. We want our model to be able to predict good in this domain as well.

In [26]:
# Here we only need the condition that at least one similarity is higher than threshold

def product_tagger_adj_high(df, text_columnn, thrsh):
    df_copy = df.copy()
    condition = (df_copy[cos_col] > thrsh).any(axis=1)
    df_copy = df_copy[condition]
    print(f'Number of tokens satisfying the condition is {df_copy.shape[0]} \n')
    num_samples = df_copy.size
    i = 0
    for ind, example in df[condition][text_columnn].items():
        try:
            annotation = input(f'Is "{example}" a product? (1 - yes, 0 - no)')
            annotation = int(annotation)
            assert annotation == 0 or annotation == 1
            df_copy.at[ind, 'tag'] = annotation
        except (AssertionError, ValueError) as e:
            num_samples = num_samples - 1
            print("Input only zeros and ones")
            continue
        i = i + 1
        if i%100 == 0:
            save = input(f'You have {i} examples. Do you want to save (y/n)?')
            if save == 'y':
                df_copy.to_csv(f'labeled_set_{100*thrsh}.csv')
    print(df_copy)

In [52]:
product_tagger_adj_high(df, 'clean', 0.9)

Number of tokens satisfying the condition is 3123

Is "Double Ottoman" a product? (1 - yes, 0 - no)0
Is "Cabinets & Cupboards" a product? (1 - yes, 0 - no)0
Is " SUMMIT Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Puzzle sofa bed" a product? (1 - yes, 0 - no)0
Is "Lamp Table" a product? (1 - yes, 0 - no)0
Is "Sofa Tables" a product? (1 - yes, 0 - no)0
Is "TABLE" a product? (1 - yes, 0 - no)0
Is "Cabinets" a product? (1 - yes, 0 - no)0
Is "2 End Table" a product? (1 - yes, 0 - no)0
Is "cafe table" a product? (1 - yes, 0 - no)0
Is "Bookshelves & Bookcases" a product? (1 - yes, 0 - no)0
Is "Lido Barstool" a product? (1 - yes, 0 - no)1
Is "Ottomans & Poufs" a product? (1 - yes, 0 - no)0
Is "Dining room table" a product? (1 - yes, 0 - no)0
Is "Buffets & Credenza" a product? (1 - yes, 0 - no)0
Is "London table lamp" a product? (1 - yes, 0 - no)1
Is "Round tables" a product? (1 - yes, 0 - no)0
Is "Dining Tables Reduced" a product? (1 - yes, 0 - no)0
Is "Laurna Dining Table" a product? (1 - yes, 0 - no)1
Is "chaise lounges" a product? (1 - yes, 0 - no)0
Is "Heyday Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Drop Chair" a product? (1 - yes, 0 - no)0
Is "Office Chairs" a product? (1 - yes, 0 - no)0
Is "Madeira dining table" a product? (1 - yes, 0 - no)1
Is "Muse Dining Table" a product? (1 - yes, 0 - no)1
Is "Bastion Stool" a product? (1 - yes, 0 - no)1
Is "Shelving" a product? (1 - yes, 0 - no)0
Is "OFFICE ROOM" a product? (1 - yes, 0 - no)0
Is "1x Levede Storage Cabinet" a product? (1 - yes, 0 - no)1
Is "Dining Tables & Bar Tables" a product? (1 - yes, 0 - no)0
Is " Shelves & Storage " a product? (1 - yes, 0 - no)0
Is "Dining Chair Set " a product? (1 - yes, 0 - no)0
Is "Backless Bar Stools" a product? (1 - yes, 0 - no)0
Is " Executive Desk" a product? (1 - yes, 0 - no)0
Is "Ottomans and beanbags" a product? (1 - yes, 0 - no)0
Is "Dining Set" a product? (1 - yes, 0 - no)0
Is "Dresser W24 x D18 x H22 " a product? (1 - yes, 0 - no)0
Is "Dresser W47 x D16 x H30 " a product? (1 - yes, 0 - no)0
Is "Eames Hang-It-All" a product? (1 - yes, 0 - no)1
Is "Sofa Table" a product? (1 - yes, 0 - no)0
Is "Kirsten lounge chair" a product? (1 - yes, 0 - no)1
Is "Wooden Shelves" a product? (1 - yes, 0 - no)0
Is "Counter Stools" a product? (1 - yes, 0 - no)0
Is "Office Chairs 8 " a product? (1 - yes, 0 - no)0
Is "EAMES WALNUT STOOL BY HERMAN MILLER" a product? (1 - yes, 0 - no)1
Is "Storage & Shelving" a product? (1 - yes, 0 - no)0
Is "dinner table" a product? (1 - yes, 0 - no)0
Is "Modern Dining Furniture" a product? (1 - yes, 0 - no)0
Is "Lockwood Grand Credenza" a product? (1 - yes, 0 - no)1
Is "Lounge" a product? (1 - yes, 0 - no)0
Is "Modern Contemporary Coffee Tables" a product? (1 - yes, 0 - no)0
Is "Bar Tables " a product? (1 - yes, 0 - no)0
Is "Double Dresser" a product? (1 - yes, 0 - no)0
Is "Conference Tables" a product? (1 - yes, 0 - no)0
Is "Miami lounge chair" a product? (1 - yes, 0 - no)1
Is "Lamp Tables" a product? (1 - yes, 0 - no)0
Is "Coffee Tables & Sets" a product? (1 - yes, 0 - no)0
Is "- Night Table" a product? (1 - yes, 0 - no)0
Is "2 Pc - Large Leg Desk Credenza" a product? (1 - yes, 0 - no)0
Is "Adjustable Height Desk NEW " a product? (1 - yes, 0 - no)0
Is "Relaxing Chairs" a product? (1 - yes, 0 - no)0
Is "Bookcases & Standing Shelves" a product? (1 - yes, 0 - no)0
Is "Bobbin Side Table" a product? (1 - yes, 0 - no)0
Is "Office Furniture" a product? (1 - yes, 0 - no)0
Is "Modern Bookcase" a product? (1 - yes, 0 - no)0
Is "Fabric sofas" a product? (1 - yes, 0 - no)0
Is "Outdoor Sofas & Beds" a product? (1 - yes, 0 - no)0
Is "Bar & Foot Stools" a product? (1 - yes, 0 - no)0
Is "Wooden Desks" a product? (1 - yes, 0 - no)0
Is "Pacha Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Billy armchair" a product? (1 - yes, 0 - no)1
Is "Lounge Chairs" a product? (1 - yes, 0 - no)0
Is "Roberta Buffet" a product? (1 - yes, 0 - no)1
Is "Office Shelves" a product? (1 - yes, 0 - no)0
Is "Lamp Table" a product? (1 - yes, 0 - no)0
Is "DINING ROOM" a product? (1 - yes, 0 - no)0
Is "Upholstered lounge chair with winged backrest and stained " a product? (1 - yes, 0 - no)0
Is "SHELVING & STORAGE" a product? (1 - yes, 0 - no)0
Is "Swivel Chair" a product? (1 - yes, 0 - no)0
Is "X Big Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Nightstand 22 W x 19 D x 18 H" a product? (1 - yes, 0 - no)0
Is "Leaf Table Lamp" a product? (1 - yes, 0 - no)1
Is "Coffee table books" a product? (1 - yes, 0 - no)0
Is " Fabric Sofas" a product? (1 - yes, 0 - no)0
Is "Merton Dresser" a product? (1 - yes, 0 - no)1
Is "Bayberry Dining Table" a product? (1 - yes, 0 - no)1
Is "Round Bedside Tables" a product? (1 - yes, 0 - no)0
Is "Nightstand L27 X D18 X H28 " a product? (1 - yes, 0 - no)0
Is "Leather Office Chairs" a product? (1 - yes, 0 - no)0
Is "Carlo Office Chair" a product? (1 - yes, 0 - no)1
Is "Sofas & Lounges" a product? (1 - yes, 0 - no)0
Is "Bookshelves" a product? (1 - yes, 0 - no)0
Is "Chest of drawers" a product? (1 - yes, 0 - no)0
Is "Dune Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Tupelo Dining Table" a product? (1 - yes, 0 - no)1
Is "Sofas Loveseats" a product? (1 - yes, 0 - no)0
Is " Sunrise Desk Chair " a product? (1 - yes, 0 - no)1
Is "Lounge Chairs" a product? (1 - yes, 0 - no)0
Is "Ottomans & Benches" a product? (1 - yes, 0 - no)0
Is "Display Shelves" a product? (1 - yes, 0 - no)0
You have 100 examples. Do you want to save (y/n)?y
Is "Office" a product? (1 - yes, 0 - no)0
Is "Lounge chairs" a product? (1 - yes, 0 - no)0
Is "Trill Barstool" a product? (1 - yes, 0 - no)1
Is "night stands dressers" a product? (1 - yes, 0 - no)0
Is "Side End Tables" a product? (1 - yes, 0 - no)0
Is "Living & Dining Furniture" a product? (1 - yes, 0 - no)0
Is "Large Dining Tables" a product? (1 - yes, 0 - no)0
Is "Risley Deluxe L-Shaped Desk" a product? (1 - yes, 0 - no)1
Is "Sofas " a product? (1 - yes, 0 - no)0
Is "Metal tube framed lounge chair with loose seat " a product? (1 - yes, 0 - no)0
Is " Blanco Dresser " a product? (1 - yes, 0 - no)1
Is "Book case" a product? (1 - yes, 0 - no)0
Is "Dining Tables " a product? (1 - yes, 0 - no)0
Is "Adjustable Height Desk NEW " a product? (1 - yes, 0 - no)0
Is "TV Console" a product? (1 - yes, 0 - no)0
Is "Sideboards & Buffets" a product? (1 - yes, 0 - no)0
Is "Platner Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Secretary Desk" a product? (1 - yes, 0 - no)0
Is "Dining tables and bar tables" a product? (1 - yes, 0 - no)0
Is " Dining Tables " a product? (1 - yes, 0 - no)0
Is " Side Tables " a product? (1 - yes, 0 - no)0
Is "Bed Dresser Mirror" a product? (1 - yes, 0 - no)0
Is "Stool" a product? (1 - yes, 0 - no)0
Is "Captain Coffee Table" a product? (1 - yes, 0 - no)1
Is "ACCENT CHAIRS" a product? (1 - yes, 0 - no)1
Is "Dressing Tables" a product? (1 - yes, 0 - no)0
Is "Wooden Side Tables" a product? (1 - yes, 0 - no)0
Is "Wall Shelves" a product? (1 - yes, 0 - no)0
Is "Sofas & Armchairs" a product? (1 - yes, 0 - no)0
Is "Sun Loungers" a product? (1 - yes, 0 - no)0
Is "Fabric Sofas" a product? (1 - yes, 0 - no)0
Is "DINING FURNITURE" a product? (1 - yes, 0 - no)0
Is " Table Desk" a product? (1 - yes, 0 - no)0
Is "Loveseats & Sofas " a product? (1 - yes, 0 - no)0
Is "Armelle Office Credenza with Hutch" a product? (1 - yes, 0 - no)1
Is "Sofas & Couches" a product? (1 - yes, 0 - no)0
Is "Scholar coffee table" a product? (1 - yes, 0 - no)1
Is " Dining Tables" a product? (1 - yes, 0 - no)0
Is "Conrad Side Table" a product? (1 - yes, 0 - no)1
Is "PEPE LOUNGE CHAIR" a product? (1 - yes, 0 - no)1
Is "Ripple - Lounge chair" a product? (1 - yes, 0 - no)1
Is "Desk Workstation - 4" a product? (1 - yes, 0 - no)1
Is "Display Cabinets" a product? (1 - yes, 0 - no)0
Is "Display Cabinet" a product? (1 - yes, 0 - no)0
Is "shelf" a product? (1 - yes, 0 - no)0
Is "Patio chairs" a product? (1 - yes, 0 - no)0
Is "Bentwood Rocking Chair" a product? (1 - yes, 0 - no)1
Is "Standing desks" a product? (1 - yes, 0 - no)0
Is "Multi-use Dining and Cafe Tables" a product? (1 - yes, 0 - no)0
Is "Corner sofa beds" a product? (1 - yes, 0 - no)0
Is "Piano desk" a product? (1 - yes, 0 - no)0
Is "Cabinetry" a product? (1 - yes, 0 - no)0
Is "Bueno Coffee Table" a product? (1 - yes, 0 - no)1

Is "3-seater Sofa" a product? (1 - yes, 0 - no)0
Is "Lucille Bedside Table" a product? (1 - yes, 0 - no)1
Is "Dressing table" a product? (1 - yes, 0 - no)0
Is "Writing Desk" a product? (1 - yes, 0 - no)0
Is "Combo Dresser" a product? (1 - yes, 0 - no)0
Is "Chardonnay Side table " a product? (1 - yes, 0 - no)1
Is "BAR STOOLS" a product? (1 - yes, 0 - no)0
Is "Storage & shelving" a product? (1 - yes, 0 - no)0
Is "Arc Dining Table " a product? (1 - yes, 0 - no)0
Is " TRI Stool" a product? (1 - yes, 0 - no)1
Is " Storage compartment" a product? (1 - yes, 0 - no)0
Is "Tv Units" a product? (1 - yes, 0 - no)0
Is "Mera Sofa" a product? (1 - yes, 0 - no)1
Is "Naruna Dining Table" a product? (1 - yes, 0 - no)1
Is "Breeze High Back Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Bed Side Night Stand" a product? (1 - yes, 0 - no)0
Is "Dining Room Benches" a product? (1 - yes, 0 - no)0
Is "Office " a product? (1 - yes, 0 - no)0
Is "Stack Of Chairs Bar Stool" a product? (1 - yes, 0 - no)1
Is "dining" a product? (1 - yes, 0 - no)0
Is "Ceiling Lamps" a product? (1 - yes, 0 - no)0
Is "DINING ROOM" a product? (1 - yes, 0 - no)0
Is "Ceiling Lamp" a product? (1 - yes, 0 - no)0
Is "Barbados Dresser" a product? (1 - yes, 0 - no)1
Is "Shelving Storage" a product? (1 - yes, 0 - no)0
Is "Chaise Cushions" a product? (1 - yes, 0 - no)0
Is "Office bookcase" a product? (1 - yes, 0 - no)0
Is "Brown Sofa" a product? (1 - yes, 0 - no)0
Is "Ottoman Benches" a product? (1 - yes, 0 - no)0
Is "Glocester L-Shaped Desk" a product? (1 - yes, 0 - no)1
Is "Dining room Furniture" a product? (1 - yes, 0 - no)0
Is "STUDY DESKS" a product? (1 - yes, 0 - no)0
Is "Belize Dinning Table" a product? (1 - yes, 0 - no)1
Is "Wave Side table" a product? (1 - yes, 0 - no)0
Is "Coronado L-Shaped Desk" a product? (1 - yes, 0 - no)
Input only zeros and ones
Is "Dresser L59 D18 H32 " a product? (1 - yes, 0 - no)0
Is "Ottoman Footstools" a product? (1 - yes, 0 - no)0
Is "Garden sofa" a product? (1 - yes, 0 - no)0
Is "Calhoun Dresser with Mirror" a product? (1 - yes, 0 - no)1
Is "Square Side Tables" a product? (1 - yes, 0 - no)0
Is "Love Chair" a product? (1 - yes, 0 - no)0
Is "Media Cabinets" a product? (1 - yes, 0 - no)0
Is "Kink barstool" a product? (1 - yes, 0 - no)1
Is "Red Sofa" a product? (1 - yes, 0 - no)0
Is "Credenzas & Sideboards" a product? (1 - yes, 0 - no)0
Is "Nod Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Alto coffee table" a product? (1 - yes, 0 - no)1
Is "Curtis Coffee Table" a product? (1 - yes, 0 - no)1
You have 200 examples. Do you want to save (y/n)?y

KeyboardInterrupt: Interrupted by user

In the end we want some examples from low similarity domain in order to have all kinds of examples seen by the model

In [53]:
product_tagger(df, 'clean', 0.8, 0)

Number of tokens satisfying the condition is 33402

Is "Kenneth Nilson" a product? (1 - yes, 0 - no)0
Is " Dania " a product? (1 - yes, 0 - no)0
Is "$1 750 00" a product? (1 - yes, 0 - no)0
Is "Prestige Navy - $5 665 00 USD" a product? (1 - yes, 0 - no)0
Is "Niger USD $ " a product? (1 - yes, 0 - no)0
Is " Grofer HB has been added to your cart " a product? (1 - yes, 0 - no)0
Is "828 80" a product? (1 - yes, 0 - no)0
Is " $809 97" a product? (1 - yes, 0 - no)0
Is "$7 187 40" a product? (1 - yes, 0 - no)0
Is "Nov 8 2019" a product? (1 - yes, 0 - no)0
Is " 3 5 kg " a product? (1 - yes, 0 - no)0
Is "Lotty Damson" a product? (1 - yes, 0 - no)0
Is "24332" a product? (1 - yes, 0 - no)0
Is "Expand submenu ACCESSORIES" a product? (1 - yes, 0 - no)0
Is "Elligton Sectional" a product? (1 - yes, 0 - no)0
Is "Rich Navy Velvet" a product? (1 - yes, 0 - no)0
Is "$ 149 SGD" a product? (1 - yes, 0 - no)0
Is "173 00" a product? (1 - yes, 0 - no)0
Is "Trade Registration" a product? (1 - yes, 0 - no)0
Is "69422" a product? (1 - yes, 0 - no)0
Is "Central African Republic USD $ " a product? (1 - yes, 0 - no)0
Is "6Colors" a product? (1 - yes, 0 - no)0
Is "Bloomingville" a product? (1 - yes, 0 - no)0
Is "25437" a product? (1 - yes, 0 - no)0
Is "1 220" a product? (1 - yes, 0 - no)0
Is "Weight 80 Kg" a product? (1 - yes, 0 - no)0
Is "Ipswich" a product? (1 - yes, 0 - no)0
Is "960 00" a product? (1 - yes, 0 - no)0
Is "Kiu collection" a product? (1 - yes, 0 - no)0
Is "FAQ S " a product? (1 - yes, 0 - no)0
Is "$2 315 30" a product? (1 - yes, 0 - no)0
Is "$3 616 76" a product? (1 - yes, 0 - no)0
Is " Apply Benches filter " a product? (1 - yes, 0 - no)0
Is "$3 499 00" a product? (1 - yes, 0 - no)0
Is "PRODUCT DETAILS" a product? (1 - yes, 0 - no)0
Is " Stig " a product? (1 - yes, 0 - no)0
Is " Shape Novelty Shape" a product? (1 - yes, 0 - no)0
Is "Safi 7776 6S11" a product? (1 - yes, 0 - no)0
Is "2 977" a product? (1 - yes, 0 - no)0
Is "$129 65" a product? (1 - yes, 0 - no)0
Is "The item was superb and outstanding Ever so nice packaging " a product? (1 - yes, 0 - no)0
Is "B9588" a product? (1 - yes, 0 - no)0
Is "Staining and finishing" a product? (1 - yes, 0 - no)0
Is "167 99" a product? (1 - yes, 0 - no)0
Is "605 00" a product? (1 - yes, 0 - no)0
Is "Slovenia EUREUR " a product? (1 - yes, 0 - no)0
Is "61 499 00" a product? (1 - yes, 0 - no)0
Is "Default Title- $179 07" a product? (1 - yes, 0 - no)0
Is "EUR259 00" a product? (1 - yes, 0 - no)0
Is "Garden Hoses & Accessories Hoses Boxes Holders Sprinklers FADS" a product? (1 - yes, 0 - no)0
Is "Robin s Egg 28 Overall Drop - $5 480 00" a product? (1 - yes, 0 - no)1
Is "283 80" a product? (1 - yes, 0 - no)0
Is "211 99" a product? (1 - yes, 0 - no)0
Is "48 hours " a product? (1 - yes, 0 - no)0
Is "COLE MASON" a product? (1 - yes, 0 - no)0
Is "$3 130 18" a product? (1 - yes, 0 - no)0
Is " Splinter " a product? (1 - yes, 0 - no)0
Is "138049" a product? (1 - yes, 0 - no)0
Is "Mirror 55 59 3 5 - Optional" a product? (1 - yes, 0 - no)0
Is " Customisable Size" a product? (1 - yes, 0 - no)0
Is "Gifts under PS50" a product? (1 - yes, 0 - no)0
Is "29392" a product? (1 - yes, 0 - no)0
Is " wooden Leg 116" a product? (1 - yes, 0 - no)0
Is "Add 5 Year Warranty $531 72 " a product? (1 - yes, 0 - no)0
Is "How to use" a product? (1 - yes, 0 - no)0
Is "206 121 35" a product? (1 - yes, 0 - no)0
Is " Mirror 47 L X 3 W X 44 H 57 3 lbs" a product? (1 - yes, 0 - no)0
Is "Adona Festival Gift Card" a product? (1 - yes, 0 - no)0
Is " MXN $ " a product? (1 - yes, 0 - no)0
Is "Pocket springs HR Foam 35 kg on top feather mixed with shredded foam" a product? (1 - yes, 0 - no)0
Is "87119888457" a product? (1 - yes, 0 - no)0
Is "Foam 30 kg" a product? (1 - yes, 0 - no)0
Is "D 775" a product? (1 - yes, 0 - no)0
Is "183 96" a product? (1 - yes, 0 - no)0
Is "Can I install my Celeste Pendant on a sloped ceiling " a product? (1 - yes, 0 - no)0
Is "The shipping cost depends on your country and the size of your order " a product? (1 - yes, 0 - no)0
Is "From $6117" a product? (1 - yes, 0 - no)0
Is "The item was outstanding Wonderful packaging Very pleased " a product? (1 - yes, 0 - no)0
Is "997 00" a product? (1 - yes, 0 - no)0
Is "$8 344 00" a product? (1 - yes, 0 - no)0
Is "Learn more about our product below " a product? (1 - yes, 0 - no)0
Is "R3 995" a product? (1 - yes, 0 - no)0
Is "New Reduced Clearance Price " a product? (1 - yes, 0 - no)0
Is "Zinolin Textile Cleaner" a product? (1 - yes, 0 - no)1
Is "From $1029" a product? (1 - yes, 0 - no)0
Is "Mr Alfredo Kling IV" a product? (1 - yes, 0 - no)0
Is "11 880 00" a product? (1 - yes, 0 - no)0
Is "Malawi USD $ " a product? (1 - yes, 0 - no)0
Is "9 302 00" a product? (1 - yes, 0 - no)0
Is "Add 5 Year Warranty $173 75 " a product? (1 - yes, 0 - no)0
Is "Color Grey F-113" a product? (1 - yes, 0 - no)0
Is "58 75 lbs " a product? (1 - yes, 0 - no)0
Is " Quality construction built to last " a product? (1 - yes, 0 - no)0
Is "Material SUNPROOF textile " a product? (1 - yes, 0 - no)0
Is "CPF001" a product? (1 - yes, 0 - no)0
Is "260 40" a product? (1 - yes, 0 - no)0
Is "Reasons for Failed Delivery" a product? (1 - yes, 0 - no)0
Is "Dot 03" a product? (1 - yes, 0 - no)0
Is "R5 995" a product? (1 - yes, 0 - no)0
Is "923 00" a product? (1 - yes, 0 - no)0
You have 100 examples. Do you want to save (y/n)?y
Is "82 99" a product? (1 - yes, 0 - no)0
Is "From $4343" a product? (1 - yes, 0 - no)0
Is "5 x " a product? (1 - yes, 0 - no)0
Is "Savannah cement" a product? (1 - yes, 0 - no)0
Is "$6 204 33" a product? (1 - yes, 0 - no)0
Is "Apr 21 2020" a product? (1 - yes, 0 - no)0
Is "Toggle Nav" a product? (1 - yes, 0 - no)0
Is "2 022 00" a product? (1 - yes, 0 - no)0
Is "fter checking out you will receive a unique code " a product? (1 - yes, 0 - no)0
Is " Width 26 66 cm Depth 25 75 65 cm Height 46 117 cm " a product? (1 - yes, 0 - no)0
Is "Michael Lysemose" a product? (1 - yes, 0 - no)0
Is "198 90" a product? (1 - yes, 0 - no)0
Is "$1 634 86" a product? (1 - yes, 0 - no)0
Is "VGJY-4016-GRY" a product? (1 - yes, 0 - no)0
Is "B9505-EK" a product? (1 - yes, 0 - no)0
Is "$24 00" a product? (1 - yes, 0 - no)0
Is "531 72" a product? (1 - yes, 0 - no)0
Is "Leather - Mont Blanc Smoke - $6 985 00 USD" a product? (1 - yes, 0 - no)0
Is "Find Out How" a product? (1 - yes, 0 - no)0
Is "You can custom build the Throne" a product? (1 - yes, 0 - no)0
Is "Stay In Touch" a product? (1 - yes, 0 - no)0
Is "Price ranges from R1 495 to R9 995" a product? (1 - yes, 0 - no)0
Is "Simplex Oyster - $1 450 00 USD" a product? (1 - yes, 0 - no)0
Is "1 009 00" a product? (1 - yes, 0 - no)0
Is "$1 962 80" a product? (1 - yes, 0 - no)0
Is "79 00" a product? (1 - yes, 0 - no)0
Is "198cm" a product? (1 - yes, 0 - no)0
Is "Select Version" a product? (1 - yes, 0 - no)0
Is "Ghana" a product? (1 - yes, 0 - no)0
Is "1 291 92" a product? (1 - yes, 0 - no)0
Is " Please Note Packed in Bulk without UPC" a product? (1 - yes, 0 - no)0
Is "99 883 00" a product? (1 - yes, 0 - no)0
Is "EUR10" a product? (1 - yes, 0 - no)0
Is "Subscribe for newsletters and receive 15 off your first order " a product? (1 - yes, 0 - no)0
Is "Las Vegas NV 89146" a product? (1 - yes, 0 - no)0
Is "Sabine Cream - $128 00" a product? (1 - yes, 0 - no)0
Is "$575" a product? (1 - yes, 0 - no)0
Is "3 599 00" a product? (1 - yes, 0 - no)0
Is "Orange and Yellow" a product? (1 - yes, 0 - no)0
Is "PS139 00" a product? (1 - yes, 0 - no)0
Is "724 92" a product? (1 - yes, 0 - no)0
Is "Coco Wood and Beads Beveled Mirror 37 Diameter x 7 Deep- $1 869 00" a product? (1 - yes, 0 - no)0
Is "Norway GBP PS " a product? (1 - yes, 0 - no)0
Is "Spread the word" a product? (1 - yes, 0 - no)0
Is " Comprehensive 7-zone support" a product? (1 - yes, 0 - no)0
Is "Easy installation on fences or walls" a product? (1 - yes, 0 - no)0
Is "Diivan Cosmo 3-kohaline" a product? (1 - yes, 0 - no)1
Is " Opening at top of globe 3 " a product? (1 - yes, 0 - no)0
Is "2 336 04" a product? (1 - yes, 0 - no)0
Is "From $851" a product? (1 - yes, 0 - no)0
Is "Add 5 Year Warranty $202 90 " a product? (1 - yes, 0 - no)0
Is "$5 667 97" a product? (1 - yes, 0 - no)0
Is "Name ascending" a product? (1 - yes, 0 - no)0
Is "54601" a product? (1 - yes, 0 - no)0

Is "jsprice" a product? (1 - yes, 0 - no)0
Is "contact adona in" a product? (1 - yes, 0 - no)0
Is "693009" a product? (1 - yes, 0 - no)0
Is "VGVCN8111-BLK-2pcs" a product? (1 - yes, 0 - no)0
Is "From $3330" a product? (1 - yes, 0 - no)0
Is "$5 577 53" a product? (1 - yes, 0 - no)0
Is "365 days FREE return policy " a product? (1 - yes, 0 - no)0
Is "12 - 26" a product? (1 - yes, 0 - no)0
Is "1 112 00" a product? (1 - yes, 0 - no)0
Is "color" a product? (1 - yes, 0 - no)0
Is "Robert Ogden" a product? (1 - yes, 0 - no)0
Is "59915" a product? (1 - yes, 0 - no)0
Is "for all UK parcel orders - next day & tracked " a product? (1 - yes, 0 - no)0
Is "RRP$540 26" a product? (1 - yes, 0 - no)0
Is "PERFORMANCE FABRICS" a product? (1 - yes, 0 - no)0
Is "AA Hanger - APATO" a product? (1 - yes, 0 - no)0
Is "139263" a product? (1 - yes, 0 - no)0
Is "3 sDIV Right or Left " a product? (1 - yes, 0 - no)0
Is "viewed cookie policy" a product? (1 - yes, 0 - no)0
Is "3 756 00" a product? (1 - yes, 0 - no)0
Is "$10 807 12" a product? (1 - yes, 0 - no)0
Is "From $957" a product? (1 - yes, 0 - no)0
Is "From $10423" a product? (1 - yes, 0 - no)0
Is "46774" a product? (1 - yes, 0 - no)0
Is "$1 860 66" a product? (1 - yes, 0 - no)0
Is "Save 10 Today " a product? (1 - yes, 0 - no)0
Is "628 32" a product? (1 - yes, 0 - no)0
Is "Bailee Quigley MD" a product? (1 - yes, 0 - no)0
Is "$3 015 00" a product? (1 - yes, 0 - no)0
Is "View account" a product? (1 - yes, 0 - no)0
Is "Dr Dakota Dietrich" a product? (1 - yes, 0 - no)0
Is "$0 to $999" a product? (1 - yes, 0 - no)0
Is "EUR10 00" a product? (1 - yes, 0 - no)0
Is "Dove 20 Overall Drop - $3 500 00" a product? (1 - yes, 0 - no)0
Is "$3 394 72" a product? (1 - yes, 0 - no)0
Is "Auckland Metro" a product? (1 - yes, 0 - no)0
Is "Supporting Change" a product? (1 - yes, 0 - no)0
Is "2 449 00" a product? (1 - yes, 0 - no)0
Is "2MHDB" a product? (1 - yes, 0 - no)0
Is "2 464" a product? (1 - yes, 0 - no)0
Is " Legs Rubber wood" a product? (1 - yes, 0 - no)0
Is "From $2229" a product? (1 - yes, 0 - no)0
Is "3 870 00" a product? (1 - yes, 0 - no)0
Is "Warsa dots - PS20 00" a product? (1 - yes, 0 - no)0
Is "May 29 2019" a product? (1 - yes, 0 - no)0
Is "Vibes Steel - $1 495 00 USD" a product? (1 - yes, 0 - no)0
You have 200 examples. Do you want to save (y/n)?y

KeyboardInterrupt: Interrupted by user

In [71]:
low = pd.read_csv('labeled_set_low.csv', index_col=[0], 
                  usecols = ['Unnamed: 0','clean', 'ada_embedding', 'tag'], nrows=200)
medium = pd.read_csv('labeled_set_medium.csv', index_col=[0], 
                  usecols = ['Unnamed: 0','clean', 'ada_embedding', 'tag'], nrows=1000)
high = pd.read_csv('labeled_set_high.csv', index_col=[0], 
                  usecols = ['Unnamed: 0','clean', 'ada_embedding', 'tag'], nrows=200)

Product percentage per distribution

In [72]:
(low.tag.sum()/(len(low)), medium.tag.sum()/(len(medium)), high.tag.sum()/(len(high)))

(0.015, 0.433, 0.265)

Now join

In [74]:
tagged_set = pd.concat([low, medium, high])

In [75]:
tagged_set

,clean,ada_embedding,tag
3,Kenneth Nilson,"[-0.012051408179104328, -0.019119305536150932,...",0.0
4,Dania,"[-0.009124724194407463, 0.003880592528730631, ...",0.0
5,$1 750 00,"[-0.00040550719131715596, 0.011903545819222927...",0.0
8,Prestige Navy - $5 665 00 USD,"[0.0036676963791251183, -0.008365873247385025,...",0.0
9,Niger USD $,"[-0.002789062215015292, -0.01558027882128954, ...",0.0
...,...,...,...
4860,Kink barstool,"[0.011534913443028927, -0.0043247416615486145,...",1.0
4916,Red Sofa,"[0.0008250460959970951, -0.0076873344369232655...",0.0
4985,Credenzas & Sideboards,"[0.0040961746126413345, -0.0027941998559981585...",0.0
5012,Nod Lounge Chair,"[-0.00554915564134717, -0.0031723971478641033,...",1.0
5031,Alto coffee table,"[-0.004637395031750202, 0.003038350259885192, ...",1.0

...and save

In [76]:
tagged_set.to_csv('tagged_set.csv')

Now lets make the validation set that will have the same distribution as the original data

In [50]:
def product_tagger_val(df, text_columnn, num_samples):
    df_copy = df.copy().sample(num_samples)
    print(f'Number of tokens satisfying the condition is {df_copy.shape[0]} \n')
    num_samples = df_copy.size
    pos_proportion = 0
    i = 0
    for ind, example in df_copy[text_columnn].items():
        try:
            annotation = input(f'Is "{example}" a product? (1 - yes, 0 - no)')
            annotation = int(annotation)
            assert annotation == 0 or annotation == 1
            df_copy.at[ind, 'tag'] = annotation
            pos_proportion = pos_proportion + annotation/num_samples
        except (AssertionError, ValueError) as e:
            num_samples = num_samples - 1
            print("Input only zeros and ones")
            continue
    # 95% confidence
    sam_var = 1.96 * math.sqrt((pos_proportion * (1-pos_proportion))/num_samples)
    print(f'Percentage of positive examples is {pos_proportion*100}% +/- {sam_var*100}% with 95% confidence')
    df_copy.to_csv(f'val_set_{num_samples}.csv')
    return

First lets exclude the training data

In [29]:
tagged_set = pd.read_pickle('../data/tagged_set_emb.pkl')

In [35]:
tag_for_join = tagged_set.drop(columns = ['clean', 'ada', 'bert'])

In [36]:
joined = df.merge(tag_for_join, how='outer', left_index=True, right_index=True, indicator=True)

In [42]:
not_tagged = joined[joined._merge == 'left_only'][['clean']]

Lets tag 500 examples

In [51]:
product_tagger_val(not_tagged, 'clean', 500)

Number of tokens satisfying the condition is 500

Is "Transitional Black Leather Upholstery C king bed Phoenix by Coaster" a product? (1 - yes, 0 - no)1
Is "Checkout" a product? (1 - yes, 0 - no)0
Is " 2339 items " a product? (1 - yes, 0 - no)0
Is "Round 13 " a product? (1 - yes, 0 - no)0
Is "497 00" a product? (1 - yes, 0 - no)0
Is "Call " a product? (1 - yes, 0 - no)0
Is "$700" a product? (1 - yes, 0 - no)0
Is "78 682 00" a product? (1 - yes, 0 - no)0
Is "24429" a product? (1 - yes, 0 - no)0
Is "Plica Chair" a product? (1 - yes, 0 - no)1
Is "2 790" a product? (1 - yes, 0 - no)0
Is "Kaona abbreviation of Kaonashi from japanese " a product? (1 - yes, 0 - no)0
Is "hand-rubbed custom wood stains" a product? (1 - yes, 0 - no)0
Is "Bow Front Cases with Step Tops" a product? (1 - yes, 0 - no)0
Is "From $4834" a product? (1 - yes, 0 - no)0
Is "Order History" a product? (1 - yes, 0 - no)0
Is " - Coffee Tables Consoles Chests Sideboards - $339" a product? (1 - yes, 0 - no)0
Is "Luxury Ikat Cushions" a product? (1 - yes, 0 - no)1
Is "Jug " a product? (1 - yes, 0 - no)0
Is "Arden Grace Piano Print Glass Topped Coffee Table" a product? (1 - yes, 0 - no)1
Is "2 Seater Sofa" a product? (1 - yes, 0 - no)0
Is "From $983" a product? (1 - yes, 0 - no)0
Is "Kids Toys" a product? (1 - yes, 0 - no)0
Is "Currencies " a product? (1 - yes, 0 - no)0
Is "ECOYA" a product? (1 - yes, 0 - no)0
Is "Feb 18 2021" a product? (1 - yes, 0 - no)0
Is "Azara by Greenington" a product? (1 - yes, 0 - no)0
Is " 84 W x 27 5 H x 16 D" a product? (1 - yes, 0 - no)0
Is "Extras " a product? (1 - yes, 0 - no)0
Is "$5 200" a product? (1 - yes, 0 - no)0
Is "BST 75 Barstool" a product? (1 - yes, 0 - no)1
Is "2 720 00" a product? (1 - yes, 0 - no)0
Is "Kumiko Cabinet Japanese Cabinets Apato Richmond Melbourne" a product? (1 - yes, 0 - no)1
Is "Fermer esc " a product? (1 - yes, 0 - no)0
Is "Mar 10 2020" a product? (1 - yes, 0 - no)0
Is "High-shine finish" a product? (1 - yes, 0 - no)0
Is "2 653 35" a product? (1 - yes, 0 - no)0
Is "STORAGE & SHELF" a product? (1 - yes, 0 - no)0
Is "GM002E" a product? (1 - yes, 0 - no)0
Is "1 126 00" a product? (1 - yes, 0 - no)0
Is "You " a product? (1 - yes, 0 - no)0
Is "Umbrella Range" a product? (1 - yes, 0 - no)0
Is "DURACORD r Large Rope Hammock - Oatmeal" a product? (1 - yes, 0 - no)1
Is "W NYLON THREAD" a product? (1 - yes, 0 - no)0
Is "LAURA JAMES" a product? (1 - yes, 0 - no)0
Is "$384 00" a product? (1 - yes, 0 - no)0
Is "Vases Candles & Votives" a product? (1 - yes, 0 - no)0
Is " Detachable plastic legs" a product? (1 - yes, 0 - no)0
Is "Seneca chair TEAL" a product? (1 - yes, 0 - no)1
Is "Bel Air Sofa Chaise" a product? (1 - yes, 0 - no)1
Is "Peter Ja" a product? (1 - yes, 0 - no)0
Is "Pawtucket Dining Table" a product? (1 - yes, 0 - no)1
Is "Hardwired - White Metal Canopy Brown - $1 043 00" a product? (1 - yes, 0 - no)0
Is "Childress Single Pedestal Table" a product? (1 - yes, 0 - no)1
Is "Gift Card" a product? (1 - yes, 0 - no)0
Is "od-coffee" a product? (1 - yes, 0 - no)0
Is " 5 zoned Bonnell spring - Different levels of support" a product? (1 - yes, 0 - no)0
Is "Benches Ottomans" a product? (1 - yes, 0 - no)0
Is "Connect Pouf" a product? (1 - yes, 0 - no)0
Is "Josephine Von" a product? (1 - yes, 0 - no)0
Is " Sophie Taeuber-Arp Living Abstraction 9 1 4 x 10 3 4 4 4 lb" a product? (1 - yes, 0 - no)0
Is "Shorefast" a product? (1 - yes, 0 - no)0
Is "Barnette Media Stand" a product? (1 - yes, 0 - no)1
Is "3-seater the length of the sofa red line should be 73-91in" a product? (1 - yes, 0 - no)0
Is "Unique Design" a product? (1 - yes, 0 - no)0
Is "From $5897" a product? (1 - yes, 0 - no)0
Is "Still Life with Red Flowers" a product? (1 - yes, 0 - no)0
Is " c Comfort Design 2023 " a product? (1 - yes, 0 - no)0
Is "Soft Weave Hammock - Navy" a product? (1 - yes, 0 - no)1
Is "Emma" a product? (1 - yes, 0 - no)0
Is "1 year" a product? (1 - yes, 0 - no)0
Is "SHARE WISHLIST" a product? (1 - yes, 0 - no)0
Is "Cafe Chairs" a product? (1 - yes, 0 - no)0
Is "KICCA BY KASTEL" a product? (1 - yes, 0 - no)1
Is "Notably superior quality The packaging was remarkably neat " a product? (1 - yes, 0 - no)0
Is "Papua New Guinea" a product? (1 - yes, 0 - no)0
Is "27 99" a product? (1 - yes, 0 - no)
Input only zeros and ones
Is "Leather - Brompton Black - $2 910 00 USD" a product? (1 - yes, 0 - no)0
Is "Gudrun Ryan" a product? (1 - yes, 0 - no)0
Is "Lounge Sofa - 8" a product? (1 - yes, 0 - no)1
Is "Enter using password -" a product? (1 - yes, 0 - no)0
Is "Cimarron Dining Chair" a product? (1 - yes, 0 - no)1
Is "3 847 00" a product? (1 - yes, 0 - no)0
Is "B3000-Q" a product? (1 - yes, 0 - no)0
Is " Lounge Chair" a product? (1 - yes, 0 - no)0
Is "316 68" a product? (1 - yes, 0 - no)0
Is "Peyton Chandelier" a product? (1 - yes, 0 - no)1
Is "Shop by Category" a product? (1 - yes, 0 - no)0
Is "Bangladesh" a product? (1 - yes, 0 - no)0
Is "Enquire Within - Sold Out" a product? (1 - yes, 0 - no)0
Is "Karo bean bag" a product? (1 - yes, 0 - no)0
Is "Eero Saarinen" a product? (1 - yes, 0 - no)0
Is " Weight 132" a product? (1 - yes, 0 - no)0
Is "Pig Table" a product? (1 - yes, 0 - no)1
Is "Gracrux Solid Fir Wood Orange Corner Trellis Planter" a product? (1 - yes, 0 - no)1
Is "NO 18 BY THONET" a product? (1 - yes, 0 - no)1
Is "Windsor Armchair Apple Green" a product? (1 - yes, 0 - no)1
Is "Buy Fabric Bedside Table - Grey Online in Australia- Factory Buys" a product? (1 - yes, 0 - no)0
Is "Dark Grey 4seater 92-118in - " a product? (1 - yes, 0 - no)0
Is "18 W x 15 D x 25 H" a product? (1 - yes, 0 - no)0
Is "Costa Chair - Verbena Jardin NZ" a product? (1 - yes, 0 - no)1
Is "Audra petit pendant" a product? (1 - yes, 0 - no)1
Is "Cape Side Chair" a product? (1 - yes, 0 - no)1
Is "BROOKING DINING TABLE" a product? (1 - yes, 0 - no)1
Is "SHOJI SHELVES" a product? (1 - yes, 0 - no)1
Is "$1 249 00" a product? (1 - yes, 0 - no)0
Is "Avalon Outdoor End Table" a product? (1 - yes, 0 - no)1
Is "Alighieri Butterfly Dining Table" a product? (1 - yes, 0 - no)1
Is "396 00" a product? (1 - yes, 0 - no)0
Is "23 Diameter 20 Overall Drop - $1 760 00" a product? (1 - yes, 0 - no)0
Is "Price ranges from R295 to R27 995" a product? (1 - yes, 0 - no)0
Is "Balancing act" a product? (1 - yes, 0 - no)0
Is "Anvil Bras side table" a product? (1 - yes, 0 - no)1
Is "Ebonised oak red orange suede" a product? (1 - yes, 0 - no)0
Is "Panel Fabrics" a product? (1 - yes, 0 - no)0
Is "Metal Frame" a product? (1 - yes, 0 - no)0
Is "Bayside Aluminum" a product? (1 - yes, 0 - no)0
Is "Americus Garden China Cabinet" a product? (1 - yes, 0 - no)1
Is "The item was super Ideal packaging An ever so good seller " a product? (1 - yes, 0 - no)0
Is "Chase office chair" a product? (1 - yes, 0 - no)1
Is "Castile" a product? (1 - yes, 0 - no)0
Is "Terms of Service" a product? (1 - yes, 0 - no)0
Is "1001" a product? (1 - yes, 0 - no)0
Is "square dining table" a product? (1 - yes, 0 - no)0
Is "5548" a product? (1 - yes, 0 - no)0
Is "Chair & Sofa Cushions" a product? (1 - yes, 0 - no)0
Is "From $5589" a product? (1 - yes, 0 - no)0
Is "Leg Columns with Freestanding Foot" a product? (1 - yes, 0 - no)0
Is "Black Jaylen Panel Bedroom Set 3 PCS" a product? (1 - yes, 0 - no)1
Is "Shipping & Delivery Fees" a product? (1 - yes, 0 - no)0
Is "Shipping & Warranty" a product? (1 - yes, 0 - no)0
Is "W1815 x D720 x H670 SH400 " a product? (1 - yes, 0 - no)0
Is "Platinum Antique Silver SKU AHST4739-EK-Set-3 Panel Bedroom Set 3 PCS" a product? (1 - yes, 0 - no)1
Is "Doga Bistrot" a product? (1 - yes, 0 - no)1
Is "1 675 00" a product? (1 - yes, 0 - no)0
Is "Buy Childrens Desks at FADS Home Style Kids Bedroom Furniture" a product? (1 - yes, 0 - no)0
Is "Valentines New Custom Furniture Furniture restoration - Page 7" a product? (1 - yes, 0 - no)0
Is "Ms Winifred Ebert III" a product? (1 - yes, 0 - no)0
Is "Scandinavian inspired" a product? (1 - yes, 0 - no)0
Is "Splinter Chair by Nendo Apato Richmond" a product? (1 - yes, 0 - no)1
Is "1x Dreamz Mattress Topper" a product? (1 - yes, 0 - no)0
Is "8311" a product? (1 - yes, 0 - no)0
Is "satin white MDF" a product? (1 - yes, 0 - no)0
Is "Meet The Team" a product? (1 - yes, 0 - no)0
Is "Cloud Blue" a product? (1 - yes, 0 - no)0

Is "Queen Size Bed 2 x Nightstands Dresser Mirror ONLY" a product? (1 - yes, 0 - no)0
Is "106 cm" a product? (1 - yes, 0 - no)0
Is "4 875 00" a product? (1 - yes, 0 - no)0
Is "Dec 6 2019" a product? (1 - yes, 0 - no)0
Is "Cocoon Lantern" a product? (1 - yes, 0 - no)1
Is "Feedback" a product? (1 - yes, 0 - no)0
Is " Exterior Fabric" a product? (1 - yes, 0 - no)0
Is "396 90" a product? (1 - yes, 0 - no)0
Is "457 00" a product? (1 - yes, 0 - no)0
Is " 55 0 kg" a product? (1 - yes, 0 - no)0
Is "W594 x D550 x H880 AH630 SH450 mm" a product? (1 - yes, 0 - no)0
Is "1 030 00" a product? (1 - yes, 0 - no)0
Is "Assembly Videos" a product? (1 - yes, 0 - no)0
Is "Grand Life Bergere Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Byron Mini Side Table" a product? (1 - yes, 0 - no)1
Is "Shipping policy" a product? (1 - yes, 0 - no)0
Is "Continental Loft Plus" a product? (1 - yes, 0 - no)0
Is "Oak Brown Medea Platform Bedroom Set 3 PCS" a product? (1 - yes, 0 - no)1
Is "814 00" a product? (1 - yes, 0 - no)0
Is "Login Signup" a product? (1 - yes, 0 - no)0
Is "Silver Birch 3 Drawers Single Dresser Contemporary Luca Home" a product? (1 - yes, 0 - no)1
Is "Gold Blue FONTAINEBLEAU Platform Bedroom Set 4 PCS" a product? (1 - yes, 0 - no)1
Is "Luxurious Navy Velvet" a product? (1 - yes, 0 - no)0
Is "Erich Crona III" a product? (1 - yes, 0 - no)0
Is "Barringer Coffee Table" a product? (1 - yes, 0 - no)1
Is "From $3623" a product? (1 - yes, 0 - no)0
Is " Riki Stool" a product? (1 - yes, 0 - no)1
Is "DINING TABLE" a product? (1 - yes, 0 - no)0
Is "Percival Lafer" a product? (1 - yes, 0 - no)0
Is "AVAILABLE IN FABRICS" a product? (1 - yes, 0 - no)0
Is "Pavia glass table 63 clear glass" a product? (1 - yes, 0 - no)1
Is "Service area" a product? (1 - yes, 0 - no)0
Is "Full Slats Box Spring Not Required " a product? (1 - yes, 0 - no)0
Is "Free Collection At Our Newport Store Monday-Friday 10am-4pm " a product? (1 - yes, 0 - no)0
Is "$1 663 70" a product? (1 - yes, 0 - no)0
Is "5 390 00" a product? (1 - yes, 0 - no)0
Is "Item was of the most superb quality Ever so neat packaging " a product? (1 - yes, 0 - no)0
Is "Kingston Ontario" a product? (1 - yes, 0 - no)0
Is "$1500 00 - $1 500 00 AUD" a product? (1 - yes, 0 - no)0
Is "Best Quality Hammocks DFOhome" a product? (1 - yes, 0 - no)0
Is "Elnath Wall Print Set Birds Eye View of New York Skyline" a product? (1 - yes, 0 - no)0
Is "599 55" a product? (1 - yes, 0 - no)0
Is "Cyan DesignVases" a product? (1 - yes, 0 - no)0
Is "Kotan Chair - Linoleum Seat - APATO" a product? (1 - yes, 0 - no)1
Is "Zinolin Textile Cleaner" a product? (1 - yes, 0 - no)1
Is "1 977 10" a product? (1 - yes, 0 - no)0
Is "Gold Accents" a product? (1 - yes, 0 - no)0
Is "Contempo Easel" a product? (1 - yes, 0 - no)1
Is "Meissa Modern Vanity LED Bathroom Mirror Cabinet Black MDF" a product? (1 - yes, 0 - no)1
Is "Please contact store for stock " a product? (1 - yes, 0 - no)0
Is "Copyright c 1986-2023 Najarian Furniture Co Inc All Rights Reserved" a product? (1 - yes, 0 - no)0
Is "341 00" a product? (1 - yes, 0 - no)0
Is "Desk Workstation - 7" a product? (1 - yes, 0 - no)1
Is "Orbital Floor" a product? (1 - yes, 0 - no)0
Is "Sideboards & Hutch" a product? (1 - yes, 0 - no)0
Is "3 305 00" a product? (1 - yes, 0 - no)0
Is "Andrew Skiles PhD" a product? (1 - yes, 0 - no)0
Is " RWFFRw " a product? (1 - yes, 0 - no)0
Is "Swing Lounge Swivel Rocker Set of 2 - White" a product? (1 - yes, 0 - no)1
Is "Kettering Dining Set" a product? (1 - yes, 0 - no)0
Is "$100 00 - $ 100 00" a product? (1 - yes, 0 - no)0
Is "Add 5 Year Warranty $238 39 " a product? (1 - yes, 0 - no)0
Is "Feliciana Rustic Kitchen Chair" a product? (1 - yes, 0 - no)1
Is "For instance author position" a product? (1 - yes, 0 - no)0
Is "Pier Twin Bar Table Base" a product? (1 - yes, 0 - no)1
Is "SHOP NEW SOFAS" a product? (1 - yes, 0 - no)0
Is "Cumaru Wood Frame " a product? (1 - yes, 0 - no)0
Is "Hopper" a product? (1 - yes, 0 - no)0
Is "The Rug Collection" a product? (1 - yes, 0 - no)0
Is "Broxton Trestle Table" a product? (1 - yes, 0 - no)1
Is "Claudio coffee table 16 " a product? (1 - yes, 0 - no)1
Is "Monroe" a product? (1 - yes, 0 - no)0
Is "Knitted bamboo fibre cover for breathability and comfort" a product? (1 - yes, 0 - no)0
Is "$1 743 00" a product? (1 - yes, 0 - no)0
Is "Amish-Made Home and Executive Office Furniture Collections" a product? (1 - yes, 0 - no)0
Is "Slik Wall Sconce" a product? (1 - yes, 0 - no)0
Is "Vern Mohr" a product? (1 - yes, 0 - no)0
Is "Kulu sideboard" a product? (1 - yes, 0 - no)1
Is "$70 00 - $70" a product? (1 - yes, 0 - no)0
Is "Sun 9AM - 6PM" a product? (1 - yes, 0 - no)0
Is "PRODUCT HIGHLIGHTS" a product? (1 - yes, 0 - no)0
Is "Website by " a product? (1 - yes, 0 - no)0
Is "Back Packs" a product? (1 - yes, 0 - no)0
Is " Fumi L-Shaped Modular Sofa - Full Leather Semi-Aniline -Cat16 " a product? (1 - yes, 0 - no)1
Is "Bette Pfannerstill" a product? (1 - yes, 0 - no)0
Is "PS230 00" a product? (1 - yes, 0 - no)0
Is "10 hrs " a product? (1 - yes, 0 - no)0
Is "49 1 2 W x 49 1 2 H" a product? (1 - yes, 0 - no)0
Is "Luxe Edition" a product? (1 - yes, 0 - no)0
Is " $29 99 - 39 99" a product? (1 - yes, 0 - no)0
Is "Romo Moon - $2 920 00 USD" a product? (1 - yes, 0 - no)0
Is "$1 325 44" a product? (1 - yes, 0 - no)0
Is "Curtis Mud Room Coat Stand" a product? (1 - yes, 0 - no)1
Is "Page 1 of 21" a product? (1 - yes, 0 - no)0
Is "Splendid quality First-class packaging First-rate service " a product? (1 - yes, 0 - no)0
Is "Rustic Cherry" a product? (1 - yes, 0 - no)0
Is "This Offer Includes King Bed two Nightstands ONLY" a product? (1 - yes, 0 - no)0
Is "35 Year Old Brand with A Story" a product? (1 - yes, 0 - no)0
Is "Elsa Frami DDS" a product? (1 - yes, 0 - no)0
Is "Anette Modern Style" a product? (1 - yes, 0 - no)0
Is "Pillows" a product? (1 - yes, 0 - no)0
Is "Contemporary Style" a product? (1 - yes, 0 - no)0
Is "2 939 00" a product? (1 - yes, 0 - no)0
Is "Spain " a product? (1 - yes, 0 - no)0
Is "Miss Out On Something Great " a product? (1 - yes, 0 - no)0
Is " Storage by Marc Krusin" a product? (1 - yes, 0 - no)0
Is "Briar FC-15743 Oak" a product? (1 - yes, 0 - no)1
Is "Rizzo Tables" a product? (1 - yes, 0 - no)0
Is "From $5034" a product? (1 - yes, 0 - no)0
Is "Shade Color" a product? (1 - yes, 0 - no)0
Is "$20 RJ Living Gift Card" a product? (1 - yes, 0 - no)0
Is "Berkshire Butterfly Leaf Dining Table" a product? (1 - yes, 0 - no)1
Is "Gift Card for Furniture & Accessories - Use As You Shop " a product? (1 - yes, 0 - no)0
Is "Samba Double Day Std & Special High Modular Sectional" a product? (1 - yes, 0 - no)1
Is "Greenery" a product? (1 - yes, 0 - no)0
Is " 3 more " a product? (1 - yes, 0 - no)0
Is "Deco Cubic Man Statue " a product? (1 - yes, 0 - no)1
Is "Pacific theme by Pixel Union" a product? (1 - yes, 0 - no)0
Is "Mauritania GBPPS " a product? (1 - yes, 0 - no)0
Is "Full-extension drawers " a product? (1 - yes, 0 - no)0
Is "Cotton Brazilian Hammock" a product? (1 - yes, 0 - no)0
Is "To obtain warranty service you must first " a product? (1 - yes, 0 - no)0
Is "Car Accessories" a product? (1 - yes, 0 - no)0
Is "ALICE CERAMICA" a product? (1 - yes, 0 - no)0
Is "Cleaning Tips" a product? (1 - yes, 0 - no)0
Is "From $4406" a product? (1 - yes, 0 - no)0
Is "Coat Paints" a product? (1 - yes, 0 - no)0
Is "Plinth around base " a product? (1 - yes, 0 - no)0
Is "1 423 00" a product? (1 - yes, 0 - no)0
Is "Notion Underground - $5 485 00 USD" a product? (1 - yes, 0 - no)0
Is "Queen Bed 89 50 x 66 50 x 68 00 " a product? (1 - yes, 0 - no)0
Is "Lynton Grey" a product? (1 - yes, 0 - no)0
Is "Sway Dining Side Chair" a product? (1 - yes, 0 - no)1
Is "Brown & Gray Queen Size Panel Bed by Crown Mark Jaymes B6580-Q-Bed" a product? (1 - yes, 0 - no)1
Is "208 794 35" a product? (1 - yes, 0 - no)0
Is "13 918 00" a product? (1 - yes, 0 - no)0
Is "Trinidad & Tobago" a product? (1 - yes, 0 - no)0
Is "AFRDI Green Tick Certification pending" a product? (1 - yes, 0 - no)0
Is "Material AL 6061 T6 high tensile alloy Solid Brass " a product? (1 - yes, 0 - no)0
Is "Bedroom Accent & Lounge Chairs" a product? (1 - yes, 0 - no)0
Is "engraved flower pattern" a product? (1 - yes, 0 - no)0
Is "Billing Zip Postal Code" a product? (1 - yes, 0 - no)0

Is " Mon - Sat 9am - 6pm" a product? (1 - yes, 0 - no)0
Is "TRADE ACCOUNTS" a product? (1 - yes, 0 - no)0
Is "From $6571" a product? (1 - yes, 0 - no)0
Is "Wool Rugs" a product? (1 - yes, 0 - no)0
Is "POUFS & OTTOMANS" a product? (1 - yes, 0 - no)0
Is "King Bed 142 W x 87 D x 61 H" a product? (1 - yes, 0 - no)0
Is " Sofa Beds" a product? (1 - yes, 0 - no)0
Is "$500 00 PICK UP " a product? (1 - yes, 0 - no)0
Is "Nov 6 2020" a product? (1 - yes, 0 - no)0
Is " c 2023 All rights reserved " a product? (1 - yes, 0 - no)0
Is "Kids Bed Safety Rails" a product? (1 - yes, 0 - no)0
Is "Living" a product? (1 - yes, 0 - no)0
Is "Atmosphere" a product? (1 - yes, 0 - no)0
Is "Contact information" a product? (1 - yes, 0 - no)0
Is "Uleg dining table" a product? (1 - yes, 0 - no)1
Is " SUBMIT" a product? (1 - yes, 0 - no)0
Is "Pictured is the Cave Creek L-Desk" a product? (1 - yes, 0 - no)0
Is "Very good service from start to end " a product? (1 - yes, 0 - no)0
Is "Systems with Storage" a product? (1 - yes, 0 - no)0
Is "Merrywood Wine Cabinet" a product? (1 - yes, 0 - no)1
Is "Marbella Mirror W39 x D1 x H39 " a product? (1 - yes, 0 - no)1
Is "Medium Bookcase - Avon Chunky Oak-- Westbridge Furniture" a product? (1 - yes, 0 - no)1
Is "The Tiffany chair otherwise known as the Chiavari " a product? (1 - yes, 0 - no)1
Is "McCall Kitchen Island" a product? (1 - yes, 0 - no)1
Is "RRP$460 46" a product? (1 - yes, 0 - no)0
Is "44 99" a product? (1 - yes, 0 - no)0
Is "Rugs & Doormats" a product? (1 - yes, 0 - no)0
Is "Arena Cove Outdoor Glider" a product? (1 - yes, 0 - no)1
Is "Meet The Designers" a product? (1 - yes, 0 - no)0
Is "7 620 90" a product? (1 - yes, 0 - no)0
Is "$3 934 00" a product? (1 - yes, 0 - no)0
Is "Mrs Syble Olson" a product? (1 - yes, 0 - no)0
Is "1x Assembly Manual" a product? (1 - yes, 0 - no)0
Is "Mar 21 2020" a product? (1 - yes, 0 - no)0
Is "Latest Offers" a product? (1 - yes, 0 - no)0
Is "KO SAMUI" a product? (1 - yes, 0 - no)0
Is "Marco" a product? (1 - yes, 0 - no)0
Is "Customised 32 " a product? (1 - yes, 0 - no)0
Is "Garden Ceiling Lamp" a product? (1 - yes, 0 - no)0
Is "Hall Seats" a product? (1 - yes, 0 - no)0
Is "DIIVANID" a product? (1 - yes, 0 - no)0
Is "Dec 26 2019" a product? (1 - yes, 0 - no)0
Is "Use " a product? (1 - yes, 0 - no)0
Is " Korento Table " a product? (1 - yes, 0 - no)1
Is "Amya Champlin" a product? (1 - yes, 0 - no)0
Is "ATLANTA DARK 90CM HIGH FOOTEND BEDSTEAD" a product? (1 - yes, 0 - no)1
Is "Add 5 Year Warranty $275 56 " a product? (1 - yes, 0 - no)0
Is "Silver Black Zuma Platform Bed" a product? (1 - yes, 0 - no)1
Is "We asked some strangers what they thought " a product? (1 - yes, 0 - no)0
Is "From $2934" a product? (1 - yes, 0 - no)0
Is "Amish Made Curio Cabinets for Storage and Display" a product? (1 - yes, 0 - no)1
Is "The item was great and good The packaging was notably fine " a product? (1 - yes, 0 - no)0
Is "Pink star - PS20 00" a product? (1 - yes, 0 - no)0
Is "Only 137 left in stock " a product? (1 - yes, 0 - no)0
Is "Saarinen Executive Chair - Arm Chair with Swivel Base" a product? (1 - yes, 0 - no)1
Is "BY NAOTO FUKASAWA" a product? (1 - yes, 0 - no)0
Is "Modern American design" a product? (1 - yes, 0 - no)0
Is "Simbiosi Suspension" a product? (1 - yes, 0 - no)0
Is "Order Swatches " a product? (1 - yes, 0 - no)0
Is "APPLY NOW" a product? (1 - yes, 0 - no)0
Is "$4 149" a product? (1 - yes, 0 - no)0
Is "Christmas Island AUD$ " a product? (1 - yes, 0 - no)0
Is " Body shape contouring" a product? (1 - yes, 0 - no)0
Is "Poodle Cloud - $1 565 00 USD" a product? (1 - yes, 0 - no)0
Is "Adira" a product? (1 - yes, 0 - no)0
Is "523 00" a product? (1 - yes, 0 - no)0
Is "QTY -17" a product? (1 - yes, 0 - no)0
Is "Contact us " a product? (1 - yes, 0 - no)0
Is "Mr Enoch Corwin DDS" a product? (1 - yes, 0 - no)0
Is "Brinxley Floor Lamp " a product? (1 - yes, 0 - no)1
Is "Feel free " a product? (1 - yes, 0 - no)0
Is "Pebble wall ceilling" a product? (1 - yes, 0 - no)0
Is "Metal Wall Hooks and Hangers" a product? (1 - yes, 0 - no)0
Is "Design Appointment" a product? (1 - yes, 0 - no)0
Is "CANYON DINING TABLE" a product? (1 - yes, 0 - no)1
Is "Queen Bed 2 x Nightstands Dresser Mirror ONLY" a product? (1 - yes, 0 - no)0
Is "The Signature of Elegance Since 1969" a product? (1 - yes, 0 - no)0
Is "60 plus vanity" a product? (1 - yes, 0 - no)0
Is "Nexa Nesting Side Table" a product? (1 - yes, 0 - no)1
Is "34080" a product? (1 - yes, 0 - no)0
Is "From $6040" a product? (1 - yes, 0 - no)0
Is "Charles Armchair Grey Chrome" a product? (1 - yes, 0 - no)1
Is "OFFICE" a product? (1 - yes, 0 - no)0
Is "Custom Shaped Banquette" a product? (1 - yes, 0 - no)0
Is "Lounge Sofa - 7" a product? (1 - yes, 0 - no)1
Is "Outdoor Swivel Chairs" a product? (1 - yes, 0 - no)1
Is "Filter by " a product? (1 - yes, 0 - no)0
Is "Howard Miller Northport Bar 693009 Home Bars USA" a product? (1 - yes, 0 - no)1
Is "From $1420" a product? (1 - yes, 0 - no)0
Is "For more info call " a product? (1 - yes, 0 - no)0
Is "662 55" a product? (1 - yes, 0 - no)0
Is " Subject" a product? (1 - yes, 0 - no)0
Is "Orbit Pendant" a product? (1 - yes, 0 - no)0
Is "Rivulet II" a product? (1 - yes, 0 - no)0
Is "$650 00" a product? (1 - yes, 0 - no)0
Is "From $868" a product? (1 - yes, 0 - no)0
Is "COP-C" a product? (1 - yes, 0 - no)0
Is "Detachable cushion with zipper" a product? (1 - yes, 0 - no)0
Is "46 6 " a product? (1 - yes, 0 - no)0
Is "Bay Minette Kitchen Table" a product? (1 - yes, 0 - no)1
Is "The item was excellent The packaging was ever so wonderful " a product? (1 - yes, 0 - no)0
Is " XAFFr " a product? (1 - yes, 0 - no)0
Is "Products Archive - Page 39 of 41 - Ginger Jar Furniture" a product? (1 - yes, 0 - no)0
Is "BOOKCASES" a product? (1 - yes, 0 - no)0
Is "The item was super Quality of the wrapping was outstanding " a product? (1 - yes, 0 - no)0
Is "Sherpa Weave" a product? (1 - yes, 0 - no)0
Is "Light Mirrors" a product? (1 - yes, 0 - no)0
Is "16 May 2019" a product? (1 - yes, 0 - no)0
Is "Rimu" a product? (1 - yes, 0 - no)0
Is "01803 712712 Mon - Fri 8 30 am - 4 30 pm" a product? (1 - yes, 0 - no)0
Is "662 00" a product? (1 - yes, 0 - no)0
Is "Bastingage White Stacking Armchair" a product? (1 - yes, 0 - no)1
Is "Divine Sectional" a product? (1 - yes, 0 - no)0
Is "Hugo Occasional Chair" a product? (1 - yes, 0 - no)1
Is "Tauranga Rotorua" a product? (1 - yes, 0 - no)0
Is "Donnelly dining table" a product? (1 - yes, 0 - no)1
Is "$270 00" a product? (1 - yes, 0 - no)0
Is "Soho Loveseat" a product? (1 - yes, 0 - no)1
Is "CAMILA" a product? (1 - yes, 0 - no)0
Is "Griffin art" a product? (1 - yes, 0 - no)0
Is "Novah Desk - DK Modern Furniture" a product? (1 - yes, 0 - no)1
Is " Aizome Cabinet " a product? (1 - yes, 0 - no)1
Is "Table Tops" a product? (1 - yes, 0 - no)0
Is "For More Information" a product? (1 - yes, 0 - no)0
Is "8 Pc Dresser Mirror Panel Bed 2 Nightstands" a product? (1 - yes, 0 - no)0
Is "Mar 23 2020" a product? (1 - yes, 0 - no)0
Is "$3 000 00" a product? (1 - yes, 0 - no)0
Is "Eagle Farm Clearance" a product? (1 - yes, 0 - no)0
Is "Pendants" a product? (1 - yes, 0 - no)0
Is "43 cm" a product? (1 - yes, 0 - no)0
Is "$3 284 40" a product? (1 - yes, 0 - no)0
Is "Germany 57" a product? (1 - yes, 0 - no)0
Is "Ellie - Bellus Furniture" a product? (1 - yes, 0 - no)0
Is "A beautiful bar chair with lots of comfort " a product? (1 - yes, 0 - no)0
Is "60cm H x 55cm W x 40cm D" a product? (1 - yes, 0 - no)0
Is "Hallstat Sofa" a product? (1 - yes, 0 - no)1
Is "PS250" a product? (1 - yes, 0 - no)0
Is " support taeillo com" a product? (1 - yes, 0 - no)0
Is "Save $59 " a product? (1 - yes, 0 - no)0
Is "Emily" a product? (1 - yes, 0 - no)0
Is "Standard seat" a product? (1 - yes, 0 - no)0
Is "Ellipticals" a product? (1 - yes, 0 - no)0
Is "Designer Boys " a product? (1 - yes, 0 - no)0
Is " $199 99" a product? (1 - yes, 0 - no)0
Is "29248" a product? (1 - yes, 0 - no)0
Is "XRJ CELEBRATION CANDLES" a product? (1 - yes, 0 - no)0
Is "W160 x D46 x H88cm" a product? (1 - yes, 0 - no)0
Is "Pace I rug" a product? (1 - yes, 0 - no)0
Is "$1 513 12" a product? (1 - yes, 0 - no)0
Is "Garden Benches - FADS" a product? (1 - yes, 0 - no)0
Is "Round Footstool" a product? (1 - yes, 0 - no)0

Is "Discounted Cushion Covers" a product? (1 - yes, 0 - no)0
Is "$10 470" a product? (1 - yes, 0 - no)0
Is "Brand Ambassador " a product? (1 - yes, 0 - no)0
Is "30 Items " a product? (1 - yes, 0 - no)0
Is "From $1948" a product? (1 - yes, 0 - no)0
Is "KN02 - Swivel and Reclining High Back Lounge Chair" a product? (1 - yes, 0 - no)1
Is "Industrial Dining Tables" a product? (1 - yes, 0 - no)0
Is "Sofa set" a product? (1 - yes, 0 - no)0
Is "18 W x 16 D x 31 H" a product? (1 - yes, 0 - no)0
Is "ROUND BARSTOOL BY THONET" a product? (1 - yes, 0 - no)1
Is "Item is of superb quality Exceptionally pleasing packaging " a product? (1 - yes, 0 - no)0
Is "3-Piece Left-Arm Fasing Cornar Chaise Sectional" a product? (1 - yes, 0 - no)0
Is "Dark Walnut Finish" a product? (1 - yes, 0 - no)0
Is "Marrakech" a product? (1 - yes, 0 - no)0
Is "Lounge Stool - W550 x D390 x H415 mm" a product? (1 - yes, 0 - no)0
Is "Filter Fine Art" a product? (1 - yes, 0 - no)0
Is "Kenton Mill Kitchen Table" a product? (1 - yes, 0 - no)1
Is "Boudoir Chair Blue " a product? (1 - yes, 0 - no)0
Is "Contemporary Vertical Chest by Luca Home" a product? (1 - yes, 0 - no)1
Is "Dome Deco" a product? (1 - yes, 0 - no)0
Is "Grey 2Pcs Cushion Covers 17x17in - " a product? (1 - yes, 0 - no)0
Is "Chelsea Sideboard White Gloss & Truffle Oak 3 Door 2 Drawer" a product? (1 - yes, 0 - no)1
Is "1 920 00" a product? (1 - yes, 0 - no)0
Is "Copyrights c 2023 KMP Furniture LLC - All Rights Reserved " a product? (1 - yes, 0 - no)0
Is "139 00" a product? (1 - yes, 0 - no)0
Is "French Chair & Arm Chair" a product? (1 - yes, 0 - no)0
Is "Metal fret work and ferrules in Whisper of Gold " a product? (1 - yes, 0 - no)0
Is "What is a drop leaf dining table and how does it work " a product? (1 - yes, 0 - no)0
Is "Bo Huels" a product? (1 - yes, 0 - no)0
Is "Enter email" a product? (1 - yes, 0 - no)0
Is "54589" a product? (1 - yes, 0 - no)0
Is "Round Rock Swivel Glider" a product? (1 - yes, 0 - no)0
Is "Cardboard" a product? (1 - yes, 0 - no)0
Is "Large Quilted Sunbrella Fabric Hammock - Expand Dove" a product? (1 - yes, 0 - no)0
Is "Add 5 Year Warranty $327 47 " a product? (1 - yes, 0 - no)0
Is "Bed Frame Collection" a product? (1 - yes, 0 - no)0
Is "For assistance call toll free 1 888 567 2228" a product? (1 - yes, 0 - no)0
Is "Alphabetically Z-A" a product? (1 - yes, 0 - no)0
Is " Finish Gray & Silver" a product? (1 - yes, 0 - no)0
Is "Styling Services" a product? (1 - yes, 0 - no)0
Is "Natural latex layer" a product? (1 - yes, 0 - no)0
Is "inquire now" a product? (1 - yes, 0 - no)0
Is "Scandinavian Bedside Tables" a product? (1 - yes, 0 - no)0
Is "Plume bed" a product? (1 - yes, 0 - no)0
Is "13272" a product? (1 - yes, 0 - no)0
Is "100 Classic Leather Chair - 100CHAIR" a product? (1 - yes, 0 - no)1
Is "Morrison Dining Chair" a product? (1 - yes, 0 - no)1
Is "Haiti GBP PS " a product? (1 - yes, 0 - no)0
Is "Natura Bebas console table" a product? (1 - yes, 0 - no)1
Is "Oxford Four Poster Bed" a product? (1 - yes, 0 - no)1
Is "2 Pc Sofa" a product? (1 - yes, 0 - no)0
Is "Natura Hairpin nesting table set" a product? (1 - yes, 0 - no)1
Is "PROVEN RELIABLE DAILY" a product? (1 - yes, 0 - no)0
Is "Gavar Bean Bag" a product? (1 - yes, 0 - no)0
Is "Silvertex Collection - Serie 2 Polyester" a product? (1 - yes, 0 - no)0
Is "Dunlopillo Noble 90cm Headboard" a product? (1 - yes, 0 - no)1
Is "ZIETA " a product? (1 - yes, 0 - no)0
Is "How long have you been in business " a product? (1 - yes, 0 - no)0
Is "PS400 00" a product? (1 - yes, 0 - no)0
Is "Whitestone King Bedroom Set 4PcsBig Valley 361W-BR Liberty Furniture" a product? (1 - yes, 0 - no)1
Is "9402-M" a product? (1 - yes, 0 - no)0
Is " Dama Bianca Collection" a product? (1 - yes, 0 - no)0
Percentage of positive examples is 20.435270541082183% +/- 3.5379874625784713% with 95% confidence

Join ada embeddings to the validation set

In [77]:
val = pd.read_csv('../data/val_set_499.csv', index_col=0)

In [78]:
val.head()

                                                   clean  tag
1116   Transitional Black Leather Upholstery C king b...  1.0
6293                                            Checkout  0.0
32879                                        2339 items   0.0
37637                                          Round 13   0.0
32213                                             497 00  0.0

In [86]:
val = val.merge(df[['ada_embedding']], how='inner', left_index=True, right_index=True)

In [90]:
val = val.dropna()

In [91]:
val.to_csv('../data/val_set_ada.csv')